// Code generated by w3cgen; DO NOT EDIT.

package xpath3_test

import (
	"os"
	"testing"

	"github.com/lestrrat-go/helium-w3c-tests/internal/harness"
)

const w3cSuiteName = "qt3"
const w3cDisplayName = "QT3"
const w3cSourceKind = "git"
const w3cSourceRepo = "https://github.com/w3c/qt3tests.git"
const w3cSourceURL = ""
const w3cPinnedCommit = "83993587711dbd5c18ed846385ec37d079d6e492"
const w3cSourceDir = "sources/qt3"
const w3cCatalogPath = "sources/qt3/catalog.xml"
const w3cCatalogTestSets = 428
const w3cCatalogTestCases = 31821
const w3cRunnableTestCases = 22090
const w3cSkippedTestCases = 383
const w3cExcludedTestCases = 9348

func TestQT3W3CManifestAvailable(t *testing.T) {
	t.Parallel()
	sourcePath := harness.SourceDir(t, w3cSourceDir)
	if _, err := os.Stat(sourcePath); err != nil {
		if os.IsNotExist(err) {
			t.Skipf("%s source tree not fetched; run %s", w3cDisplayName, "go run ./cmd/w3cgen fetch qt3")
		}
		t.Fatalf("stat %s source tree: %v", w3cDisplayName, err)
	}
	if w3cCatalogPath == "" {
		t.Logf("%s source tree present at %s; no catalog file was found", w3cDisplayName, sourcePath)
		return
	}
	t.Logf("%s catalog %s: %d test sets, %d test cases (%d runnable, %d skipped, %d excluded)", w3cDisplayName, w3cCatalogPath, w3cCatalogTestSets, w3cCatalogTestCases, w3cRunnableTestCases, w3cSkippedTestCases, w3cExcludedTestCases)
}
