// Code generated by w3cgen; DO NOT EDIT.

package xslt3_test

import (
	"os"
	"testing"

	"github.com/lestrrat-go/helium-w3c-tests/internal/harness"
)

const w3cSuiteName = "xslt30"
const w3cDisplayName = "XSLT 3.0"
const w3cSourceKind = "git"
const w3cSourceRepo = "https://github.com/w3c/xslt30-test.git"
const w3cSourceURL = ""
const w3cPinnedCommit = "6f8fd9e966ae74a251a2604abef9d904c7bc5c9b"
const w3cSourceDir = "sources/xslt30"
const w3cCatalogPath = "sources/xslt30/catalog.xml"
const w3cCatalogTestSets = 234
const w3cCatalogTestCases = 14600
const w3cRunnableTestCases = 13048
const w3cSkippedTestCases = 79
const w3cExcludedTestCases = 1473

func TestXSLT30W3CManifestAvailable(t *testing.T) {
	t.Parallel()
	sourcePath := harness.SourceDir(t, w3cSourceDir)
	if _, err := os.Stat(sourcePath); err != nil {
		if os.IsNotExist(err) {
			t.Skipf("%s source tree not fetched; run %s", w3cDisplayName, "go run ./cmd/w3cgen fetch xslt30")
		}
		t.Fatalf("stat %s source tree: %v", w3cDisplayName, err)
	}
	if w3cCatalogPath == "" {
		t.Logf("%s source tree present at %s; no catalog file was found", w3cDisplayName, sourcePath)
		return
	}
	t.Logf("%s catalog %s: %d test sets, %d test cases (%d runnable, %d skipped, %d excluded)", w3cDisplayName, w3cCatalogPath, w3cCatalogTestSets, w3cCatalogTestCases, w3cRunnableTestCases, w3cSkippedTestCases, w3cExcludedTestCases)
}
