package xml

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/lestrrat-go/helium-w3c-tests/internal/generator"
)

// catalogSubdir is the single top-level directory the W3C xmlts zip nests every
// file under; the suite root (holding xmlconf.xml) is sources/xml/xmlconf.
const catalogSubdir = "xmlconf"

type Suite struct{}

func New() Suite {
	return Suite{}
}

func (Suite) Name() string {
	return "xml"
}

// Fetch downloads and extracts the pinned W3C zip, then copies the fixtures its
// catalog references (every test document, its OUTPUT, and the transitive
// closure of external DTD/entity references) from sources/xml into
// testdata/xml, preserving the suite-root-relative layout so DTD and entity
// SYSTEM references resolve at test time.
func (s Suite) Fetch(ctx context.Context, genCtx generator.Context, suiteLock generator.SuiteLock) error {
	if err := generator.FetchSource(ctx, genCtx.Root, s.Name(), suiteLock); err != nil {
		return err
	}
	return s.populateFixtures(genCtx.Root, suiteLock)
}

func (s Suite) catalogRoot(root string, suiteLock generator.SuiteLock) string {
	return filepath.Join(root, filepath.FromSlash(suiteLock.SourceDir), catalogSubdir)
}

func (s Suite) populateFixtures(root string, suiteLock generator.SuiteLock) error {
	xmlconfRoot := s.catalogRoot(root, suiteLock)
	byCollection, _, _, err := readCases(xmlconfRoot)
	if err != nil {
		return err
	}

	destRoot := filepath.Join(root, "testdata", "xml")
	rels := FixtureRelsUnion(byCollection)
	for _, rel := range rels {
		src, err := generator.ContainedPath(xmlconfRoot, rel)
		if err != nil {
			return fmt.Errorf("resolve fixture %q: %w", rel, err)
		}
		dst, err := generator.ContainedPath(destRoot, rel)
		if err != nil {
			return fmt.Errorf("resolve fixture dest %q: %w", rel, err)
		}
		if err := copyFile(src, dst); err != nil {
			return err
		}
	}
	fmt.Printf("xml: copied %d fixtures into testdata/xml\n", len(rels))
	return nil
}

func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return fmt.Errorf("create fixture dir for %s: %w", dst, err)
	}
	in, err := os.Open(src) //nolint:gosec // src is contained under the suite root
	if err != nil {
		return fmt.Errorf("open fixture %s: %w", src, err)
	}
	defer in.Close()
	out, err := os.Create(dst) //nolint:gosec // dst is contained under testdata/xml
	if err != nil {
		return fmt.Errorf("create fixture %s: %w", dst, err)
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return fmt.Errorf("copy fixture %s: %w", dst, err)
	}
	if err := out.Close(); err != nil {
		return fmt.Errorf("close fixture %s: %w", dst, err)
	}
	return nil
}

func (s Suite) Generate(ctx context.Context, genCtx generator.Context, suiteLock generator.SuiteLock, mode generator.GenerateMode) error {
	_ = ctx
	xmlconfRoot := s.catalogRoot(genCtx.Root, suiteLock)

	info := generator.CatalogInfo{SourceDir: suiteLock.SourceDir}
	var byCollection map[string][]genCase
	var collections []string
	// Presence is decided by the SOURCE DIR (sources/xml), not the nested catalog
	// root: an absent source dir is a legitimately-unfetched checkout (emit the
	// skip-only manifest), but a PRESENT source dir with a missing/corrupt catalog
	// is a hard error — readCases fails on a missing xmlconf.xml or referenced
	// catalog rather than silently generating a zero-count suite.
	sourceDir := filepath.Join(genCtx.Root, filepath.FromSlash(suiteLock.SourceDir))
	if _, err := os.Stat(sourceDir); err != nil {
		if !os.IsNotExist(err) {
			return fmt.Errorf("stat %s: %w", suiteLock.SourceDir, err)
		}
	} else {
		info.Present = true
		info.CatalogPath = filepath.ToSlash(filepath.Join(suiteLock.SourceDir, catalogSubdir, "xmlconf.xml"))
		var testsOut int
		byCollection, collections, testsOut, err = readCases(xmlconfRoot)
		if err != nil {
			return err
		}
		info.TestSetCount = len(collections)
		info.TestCaseCount = testsOut
		info.RunnableCount = testsOut
	}

	manifest := generator.ManifestTestSource(generator.ManifestTest{
		PackageName:  "xml_test",
		TestName:     "TestXMLW3CManifestAvailable",
		DisplayName:  "XML Conformance",
		SuiteName:    s.Name(),
		FetchCommand: "go run ./cmd/w3cgen fetch xml",
		Lock:         suiteLock,
		Catalog:      info,
	})
	if err := generator.WriteGoFile(filepath.Join(genCtx.Root, "xml", "xml_manifest_gen_test.go"), manifest, mode); err != nil {
		return err
	}

	for _, collection := range collections {
		source := casesSource(collection, byCollection[collection])
		out := filepath.Join(genCtx.Root, "xml", "xml_"+collection+"_gen_test.go")
		if err := generator.WriteGoFile(out, source, mode); err != nil {
			return err
		}
	}
	return nil
}

func casesSource(collection string, cases []genCase) string {
	varName := "xml" + exportName(collection) + "Cases"

	var b strings.Builder
	b.WriteString("// Code generated by w3cgen; DO NOT EDIT.\n\n")
	b.WriteString("package xml_test\n\n")
	fmt.Fprintf(&b, "var %s = []xmlCase{\n", varName)
	for _, c := range cases {
		b.WriteString("\t{\n")
		fmt.Fprintf(&b, "\t\tID: %s,\n", strconv.Quote(c.ID))
		fmt.Fprintf(&b, "\t\tType: %s,\n", strconv.Quote(c.Type))
		fmt.Fprintf(&b, "\t\tURI: %s,\n", strconv.Quote(c.URI))
		if c.Output != "" {
			fmt.Fprintf(&b, "\t\tOutput: %s,\n", strconv.Quote(c.Output))
		}
		if c.Entities != "" {
			fmt.Fprintf(&b, "\t\tEntities: %s,\n", strconv.Quote(c.Entities))
		}
		if c.Recommendation != "" {
			fmt.Fprintf(&b, "\t\tRecommendation: %s,\n", strconv.Quote(c.Recommendation))
		}
		if c.Version != "" {
			fmt.Fprintf(&b, "\t\tVersion: %s,\n", strconv.Quote(c.Version))
		}
		if c.Edition != "" {
			fmt.Fprintf(&b, "\t\tEdition: %s,\n", strconv.Quote(c.Edition))
		}
		if c.Namespace != "" {
			fmt.Fprintf(&b, "\t\tNamespace: %s,\n", strconv.Quote(c.Namespace))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "func init() { xmlAllCases = append(xmlAllCases, %s...) }\n", varName)
	return b.String()
}

// exportName renders a collection key as a Go identifier fragment
// (xmltest → Xmltest). Collection keys are already [a-z]+ so only the first
// letter needs upcasing.
func exportName(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
