// Package xmldsig_test runs two W3C XML-Signature interoperability suites
// against helium's c14n, xpath1, and xmldsig1 packages:
//
//   - TestXMLDSig2EdW3C — the "C14N 1.1 and XMLDSig Interoperability" Note
//     (10 June 2008): pure Canonical XML 1.1 node-set cases plus signature
//     verification cases. Vectors are vendored under fixtures/xmldsig2ed and
//     overlaid into testdata/xmldsig2ed by `w3cgen fetch xmldsig2ed`.
//
//   - TestXMLDSig11W3C — the "XML Signature 1.1 Interop" enveloping-signature
//     vectors (oracle vendor set), pinned to an Apache Santuario release and
//     copied into testdata/xmldsig11 by `w3cgen fetch xmldsig11`.
//
// Case tables are generated by internal/suites/xmldsig2ed and
// internal/suites/xmldsig11; the runners and expectations live alongside them.
package xmldsig_test
