// Code generated by w3cgen; DO NOT EDIT.

package xmldsig_test

var merlinXMLDSigCases = []merlinCase{
	{
		ID:   "signature-enveloped-dsa",
		File: "signature-enveloped-dsa.xml",
	},
	{
		ID:   "signature-enveloping-b64-dsa",
		File: "signature-enveloping-b64-dsa.xml",
	},
	{
		ID:   "signature-enveloping-dsa",
		File: "signature-enveloping-dsa.xml",
	},
	{
		ID:       "signature-enveloping-hmac-sha1-40",
		File:     "signature-enveloping-hmac-sha1-40.xml",
		MustFail: true,
	},
	{
		ID:   "signature-enveloping-hmac-sha1",
		File: "signature-enveloping-hmac-sha1.xml",
	},
	{
		ID:   "signature-enveloping-rsa",
		File: "signature-enveloping-rsa.xml",
	},
	{
		ID:   "signature-external-b64-dsa",
		File: "signature-external-b64-dsa.xml",
	},
	{
		ID:   "signature-external-dsa",
		File: "signature-external-dsa.xml",
	},
	{
		ID:   "signature-keyname",
		File: "signature-keyname.xml",
	},
	{
		ID:   "signature-retrievalmethod-rawx509crt",
		File: "signature-retrievalmethod-rawx509crt.xml",
	},
	{
		ID:   "signature-x509-crt-crl",
		File: "signature-x509-crt-crl.xml",
	},
	{
		ID:   "signature-x509-crt",
		File: "signature-x509-crt.xml",
	},
	{
		ID:   "signature-x509-is",
		File: "signature-x509-is.xml",
	},
	{
		ID:   "signature-x509-ski",
		File: "signature-x509-ski.xml",
	},
	{
		ID:   "signature-x509-sn",
		File: "signature-x509-sn.xml",
	},
	{
		ID:   "signature",
		File: "signature.xml",
	},
}
