// Code generated by w3cgen; DO NOT EDIT.

package xmldsig_test

var xmldsig2edC14NCases = []dsig2edC14NCase{
	{
		ID:     "c14n11-xmlbase-c14n11spec-102",
		Input:  "c14n11/xmlbase-c14n11spec-input.xml",
		XPath:  "c14n11/xmlbase-c14n11spec-102.xpath",
		Output: "c14n11/xmlbase-c14n11spec-102.output",
	},
	{
		ID:     "c14n11-xmlbase-c14n11spec2-102",
		Input:  "c14n11/xmlbase-c14n11spec2-input.xml",
		XPath:  "c14n11/xmlbase-c14n11spec2-102.xpath",
		Output: "c14n11/xmlbase-c14n11spec2-102.output",
	},
	{
		ID:     "c14n11-xmlbase-c14n11spec3-103",
		Input:  "c14n11/xmlbase-c14n11spec3-input.xml",
		XPath:  "c14n11/xmlbase-c14n11spec3-103.xpath",
		Output: "c14n11/xmlbase-c14n11spec3-103.output",
	},
	{
		ID:     "c14n11-xmlbase-prop-1",
		Input:  "c14n11/xmlbase-prop-input.xml",
		XPath:  "c14n11/xmlbase-prop-1.xpath",
		Output: "c14n11/xmlbase-prop-1.output",
	},
	{
		ID:     "c14n11-xmlbase-prop-2",
		Input:  "c14n11/xmlbase-prop-input.xml",
		XPath:  "c14n11/xmlbase-prop-2.xpath",
		Output: "c14n11/xmlbase-prop-2.output",
	},
	{
		ID:     "c14n11-xmlbase-prop-3",
		Input:  "c14n11/xmlbase-prop-input.xml",
		XPath:  "c14n11/xmlbase-prop-3.xpath",
		Output: "c14n11/xmlbase-prop-3.output",
	},
	{
		ID:     "c14n11-xmlbase-prop-4",
		Input:  "c14n11/xmlbase-prop-input.xml",
		XPath:  "c14n11/xmlbase-prop-4.xpath",
		Output: "c14n11/xmlbase-prop-4.output",
	},
	{
		ID:     "c14n11-xmlbase-prop-5",
		Input:  "c14n11/xmlbase-prop-input.xml",
		XPath:  "c14n11/xmlbase-prop-5.xpath",
		Output: "c14n11/xmlbase-prop-5.output",
	},
	{
		ID:     "c14n11-xmlbase-prop-6",
		Input:  "c14n11/xmlbase-prop-input.xml",
		XPath:  "c14n11/xmlbase-prop-6.xpath",
		Output: "c14n11/xmlbase-prop-6.output",
	},
	{
		ID:     "c14n11-xmlbase-prop-7",
		Input:  "c14n11/xmlbase-prop-input.xml",
		XPath:  "c14n11/xmlbase-prop-7.xpath",
		Output: "c14n11/xmlbase-prop-7.output",
	},
	{
		ID:     "c14n11-xmlid-1",
		Input:  "c14n11/xmlid-input.xml",
		XPath:  "c14n11/xmlid-1.xpath",
		Output: "c14n11/xmlid-1.output",
	},
	{
		ID:     "c14n11-xmlid-2",
		Input:  "c14n11/xmlid-input.xml",
		XPath:  "c14n11/xmlid-2.xpath",
		Output: "c14n11/xmlid-2.output",
	},
	{
		ID:     "c14n11-xmllang-1",
		Input:  "c14n11/xmllang-input.xml",
		XPath:  "c14n11/xmllang-1.xpath",
		Output: "c14n11/xmllang-1.output",
	},
	{
		ID:     "c14n11-xmllang-2",
		Input:  "c14n11/xmllang-input.xml",
		XPath:  "c14n11/xmllang-2.xpath",
		Output: "c14n11/xmllang-2.output",
	},
	{
		ID:     "c14n11-xmllang-3",
		Input:  "c14n11/xmllang-input.xml",
		XPath:  "c14n11/xmllang-3.xpath",
		Output: "c14n11/xmllang-3.output",
	},
	{
		ID:     "c14n11-xmllang-4",
		Input:  "c14n11/xmllang-input.xml",
		XPath:  "c14n11/xmllang-4.xpath",
		Output: "c14n11/xmllang-4.output",
	},
	{
		ID:     "c14n11-xmlspace-1",
		Input:  "c14n11/xmlspace-input.xml",
		XPath:  "c14n11/xmlspace-1.xpath",
		Output: "c14n11/xmlspace-1.output",
	},
	{
		ID:     "c14n11-xmlspace-2",
		Input:  "c14n11/xmlspace-input.xml",
		XPath:  "c14n11/xmlspace-2.xpath",
		Output: "c14n11/xmlspace-2.output",
	},
	{
		ID:     "c14n11-xmlspace-3",
		Input:  "c14n11/xmlspace-input.xml",
		XPath:  "c14n11/xmlspace-3.xpath",
		Output: "c14n11/xmlspace-3.output",
	},
	{
		ID:     "c14n11-xmlspace-4",
		Input:  "c14n11/xmlspace-input.xml",
		XPath:  "c14n11/xmlspace-4.xpath",
		Output: "c14n11/xmlspace-4.output",
	},
}

var xmldsig2edSigCases = []dsig2edSigCase{
	{
		ID:    "sig-defCan-1-signature",
		Group: "defCan",
		Input: "xmldsig/defCan-1-signature.xml",
	},
	{
		ID:    "sig-defCan-2-signature",
		Group: "defCan",
		Input: "xmldsig/defCan-2-signature.xml",
	},
	{
		ID:    "sig-defCan-3-signature",
		Group: "defCan",
		Input: "xmldsig/defCan-3-signature.xml",
	},
	{
		ID:    "sig-diffRFCs-1-SUN",
		Group: "dname",
		Input: "xmldsig/dname/diffRFCs-1-SUN.xml",
	},
	{
		ID:    "sig-diffRFCs-2-SUN",
		Group: "dname",
		Input: "xmldsig/dname/diffRFCs-2-SUN.xml",
	},
	{
		ID:    "sig-diffRFCs-3-SUN",
		Group: "dname",
		Input: "xmldsig/dname/diffRFCs-3-SUN.xml",
	},
	{
		ID:    "sig-diffRFCs-4-SUN",
		Group: "dname",
		Input: "xmldsig/dname/diffRFCs-4-SUN.xml",
	},
	{
		ID:    "sig-diffRFCs-5-SUN",
		Group: "dname",
		Input: "xmldsig/dname/diffRFCs-5-SUN.xml",
	},
	{
		ID:    "sig-dnString-4-SUN",
		Group: "dname",
		Input: "xmldsig/dname/dnString-4-SUN.xml",
	},
	{
		ID:    "sig-dnString-6-SUN",
		Group: "dname",
		Input: "xmldsig/dname/dnString-6-SUN.xml",
	},
	{
		ID:    "sig-dnString-8-SUN",
		Group: "dname",
		Input: "xmldsig/dname/dnString-8-SUN.xml",
	},
	{
		ID:    "sig-xpointer-1-SUN",
		Group: "xpointer",
		Input: "xmldsig/xpointer/xpointer-1-SUN.xml",
	},
	{
		ID:    "sig-xpointer-2-SUN",
		Group: "xpointer",
		Input: "xmldsig/xpointer/xpointer-2-SUN.xml",
	},
	{
		ID:    "sig-xpointer-3-SUN",
		Group: "xpointer",
		Input: "xmldsig/xpointer/xpointer-3-SUN.xml",
	},
	{
		ID:    "sig-xpointer-4-SUN",
		Group: "xpointer",
		Input: "xmldsig/xpointer/xpointer-4-SUN.xml",
	},
	{
		ID:    "sig-xpointer-5-SUN",
		Group: "xpointer",
		Input: "xmldsig/xpointer/xpointer-5-SUN.xml",
	},
	{
		ID:    "sig-xpointer-6-SUN",
		Group: "xpointer",
		Input: "xmldsig/xpointer/xpointer-6-SUN.xml",
	},
}
