// Code generated by w3cgen; DO NOT EDIT.

package xmldsig_test

var xmldsig11Cases = []dsig11Case{
	{
		ID:   "signature-enveloping-hmac-sha256",
		File: "oracle/signature-enveloping-hmac-sha256.xml",
	},
	{
		ID:   "signature-enveloping-hmac-sha384",
		File: "oracle/signature-enveloping-hmac-sha384.xml",
	},
	{
		ID:   "signature-enveloping-hmac-sha512",
		File: "oracle/signature-enveloping-hmac-sha512.xml",
	},
	{
		ID:   "signature-enveloping-p256_sha1",
		File: "oracle/signature-enveloping-p256_sha1.xml",
	},
	{
		ID:   "signature-enveloping-p256_sha1_4050",
		File: "oracle/signature-enveloping-p256_sha1_4050.xml",
	},
	{
		ID:   "signature-enveloping-p256_sha256",
		File: "oracle/signature-enveloping-p256_sha256.xml",
	},
	{
		ID:   "signature-enveloping-p256_sha256_4050",
		File: "oracle/signature-enveloping-p256_sha256_4050.xml",
	},
	{
		ID:   "signature-enveloping-p256_sha384",
		File: "oracle/signature-enveloping-p256_sha384.xml",
	},
	{
		ID:   "signature-enveloping-p256_sha384_4050",
		File: "oracle/signature-enveloping-p256_sha384_4050.xml",
	},
	{
		ID:   "signature-enveloping-p256_sha512",
		File: "oracle/signature-enveloping-p256_sha512.xml",
	},
	{
		ID:   "signature-enveloping-p256_sha512_4050",
		File: "oracle/signature-enveloping-p256_sha512_4050.xml",
	},
	{
		ID:   "signature-enveloping-p384_sha1",
		File: "oracle/signature-enveloping-p384_sha1.xml",
	},
	{
		ID:   "signature-enveloping-p384_sha1_4050",
		File: "oracle/signature-enveloping-p384_sha1_4050.xml",
	},
	{
		ID:   "signature-enveloping-p384_sha256",
		File: "oracle/signature-enveloping-p384_sha256.xml",
	},
	{
		ID:   "signature-enveloping-p384_sha256_4050",
		File: "oracle/signature-enveloping-p384_sha256_4050.xml",
	},
	{
		ID:   "signature-enveloping-p384_sha384",
		File: "oracle/signature-enveloping-p384_sha384.xml",
	},
	{
		ID:   "signature-enveloping-p384_sha384_4050",
		File: "oracle/signature-enveloping-p384_sha384_4050.xml",
	},
	{
		ID:   "signature-enveloping-p384_sha512",
		File: "oracle/signature-enveloping-p384_sha512.xml",
	},
	{
		ID:   "signature-enveloping-p384_sha512_4050",
		File: "oracle/signature-enveloping-p384_sha512_4050.xml",
	},
	{
		ID:   "signature-enveloping-p521_sha1",
		File: "oracle/signature-enveloping-p521_sha1.xml",
	},
	{
		ID:   "signature-enveloping-p521_sha1_4050",
		File: "oracle/signature-enveloping-p521_sha1_4050.xml",
	},
	{
		ID:   "signature-enveloping-p521_sha256",
		File: "oracle/signature-enveloping-p521_sha256.xml",
	},
	{
		ID:   "signature-enveloping-p521_sha256_4050",
		File: "oracle/signature-enveloping-p521_sha256_4050.xml",
	},
	{
		ID:   "signature-enveloping-p521_sha384",
		File: "oracle/signature-enveloping-p521_sha384.xml",
	},
	{
		ID:   "signature-enveloping-p521_sha384_4050",
		File: "oracle/signature-enveloping-p521_sha384_4050.xml",
	},
	{
		ID:   "signature-enveloping-p521_sha512",
		File: "oracle/signature-enveloping-p521_sha512.xml",
	},
	{
		ID:   "signature-enveloping-p521_sha512_4050",
		File: "oracle/signature-enveloping-p521_sha512_4050.xml",
	},
	{
		ID:   "signature-enveloping-rsa-sha256",
		File: "oracle/signature-enveloping-rsa-sha256.xml",
	},
	{
		ID:   "signature-enveloping-rsa_sha384",
		File: "oracle/signature-enveloping-rsa_sha384.xml",
	},
	{
		ID:   "signature-enveloping-rsa_sha512",
		File: "oracle/signature-enveloping-rsa_sha512.xml",
	},
	{
		ID:   "signature-enveloping-sha256-rsa-sha256",
		File: "oracle/signature-enveloping-sha256-rsa-sha256.xml",
	},
	{
		ID:   "signature-enveloping-sha384-rsa_sha256",
		File: "oracle/signature-enveloping-sha384-rsa_sha256.xml",
	},
	{
		ID:   "signature-enveloping-sha512-rsa_sha256",
		File: "oracle/signature-enveloping-sha512-rsa_sha256.xml",
	},
}
