// Package xml_test runs the W3C XML Conformance Test Suite (xmlconf) against
// helium's parser. The per-collection case tables are generated by
// internal/suites/xml; the runner and expectations live alongside them.
package xml_test
