// Code generated by w3cgen; DO NOT EDIT.

package xml_test

var xmlJapaneseCases = []xmlCase{
	{
		ID:       "pr-xml-euc-jp",
		Type:     "error",
		URI:      "japanese/pr-xml-euc-jp.xml",
		Entities: "parameter",
	},
	{
		ID:       "pr-xml-iso-2022-jp",
		Type:     "error",
		URI:      "japanese/pr-xml-iso-2022-jp.xml",
		Entities: "parameter",
	},
	{
		ID:       "pr-xml-little",
		Type:     "valid",
		URI:      "japanese/pr-xml-little-endian.xml",
		Entities: "parameter",
	},
	{
		ID:       "pr-xml-shift_jis",
		Type:     "error",
		URI:      "japanese/pr-xml-shift_jis.xml",
		Entities: "parameter",
	},
	{
		ID:       "pr-xml-utf-16",
		Type:     "valid",
		URI:      "japanese/pr-xml-utf-16.xml",
		Entities: "parameter",
	},
	{
		ID:       "pr-xml-utf-8",
		Type:     "valid",
		URI:      "japanese/pr-xml-utf-8.xml",
		Entities: "parameter",
	},
	{
		ID:       "weekly-euc-jp",
		Type:     "error",
		URI:      "japanese/weekly-euc-jp.xml",
		Entities: "parameter",
	},
	{
		ID:       "weekly-iso-2022-jp",
		Type:     "error",
		URI:      "japanese/weekly-iso-2022-jp.xml",
		Entities: "parameter",
	},
	{
		ID:       "weekly-little",
		Type:     "valid",
		URI:      "japanese/weekly-little-endian.xml",
		Entities: "parameter",
	},
	{
		ID:       "weekly-shift_jis",
		Type:     "error",
		URI:      "japanese/weekly-shift_jis.xml",
		Entities: "parameter",
	},
	{
		ID:       "weekly-utf-16",
		Type:     "valid",
		URI:      "japanese/weekly-utf-16.xml",
		Entities: "parameter",
	},
	{
		ID:       "weekly-utf-8",
		Type:     "valid",
		URI:      "japanese/weekly-utf-8.xml",
		Entities: "parameter",
	},
}

func init() { xmlAllCases = append(xmlAllCases, xmlJapaneseCases...) }
