package xml_test

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lestrrat-go/helium"
	"github.com/lestrrat-go/helium-w3c-tests/internal/harness"
)

// containedPath joins root and a testdata-relative slash path, rejecting an
// absolute or escaping rel. Catalog @URI values are upstream-controlled data, so
// the runner refuses to read a fixture outside the testdata root even though the
// pinned suite contains none.
func containedPath(root, rel string) (string, bool) {
	clean := filepath.Clean(filepath.Join(root, filepath.FromSlash(rel)))
	r, err := filepath.Rel(root, clean)
	if err != nil || r == ".." || strings.HasPrefix(r, ".."+string(filepath.Separator)) {
		return "", false
	}
	return clean, true
}

// xmlCase is a single W3C XML Conformance Test Suite (xmlconf) test, restricted
// to the attributes the runner consults. URI (and Output) are testdata/xml-
// relative slash paths; the fixture bytes live under testdata/xml (gitignored,
// populated by `go run ./cmd/w3cgen fetch xml`).
//
// The per-collection slices (xmlXmltestCases, xmlSunCases, ...) are generated by
// internal/suites/xml into xml_<collection>_gen_test.go and each registers
// itself into xmlAllCases via an init function.
type xmlCase struct {
	ID             string
	Type           string // valid | invalid | not-wf | error
	URI            string
	Output         string
	Entities       string // none | parameter | general | both
	Recommendation string // XML1.0 | XML1.1 | NS1.0 | NS1.1 | ...
	Version        string // "" | 1.0 | 1.1
	Edition        string // space-separated 1.0 editions the test applies to
	Namespace      string // "" | yes | no
}

// xmlAllCases is populated by the generated per-collection files' init funcs.
var xmlAllCases []xmlCase

// xml11Supported gates the XML 1.1 / Namespaces 1.1 buckets. Helium targets XML
// 1.0 + Namespaces 1.0; the 1.1 cases are skipped structurally until 1.1 parser
// support lands, at which point this flips to true.
const xml11Supported = false

// targetEdition is the XML 1.0 edition helium implements. Helium ports libxml2,
// which follows the 5th edition: it replaced the 4th-edition enumerated name
// character classes (BaseChar, Ideographic, CombiningChar, Digit, Extender —
// productions [85]–[89]) with the broad NameStartChar/NameChar ranges. A TEST
// tagged for editions that exclude this one (EDITION="1 2 3 4") asserts an
// outcome — usually a not-wf rejection of a name character legal in 5th edition
// — that does not hold for a 5th-edition processor, so it is out of scope. Every
// such case in the suite is accepted by libxml2, confirming the divergence is
// edition, not a helium defect.
const targetEdition = "5"

// confinedFS is the FS helium resolves external DTD/entity SYSTEM references
// through. It normalizes OS-specific separators to forward slashes (helium may
// hand the FS backslashes for a local BaseURI on Windows) and — because those
// SYSTEM paths are upstream-controlled catalog data — rejects any name that
// escapes the testdata root before delegating to os.DirFS, so a "../" in a
// fixture cannot reach outside testdata/xml.
type confinedFS struct {
	root string
	fsys fs.FS
}

func newConfinedFS(root string) confinedFS {
	return confinedFS{root: root, fsys: os.DirFS(root)}
}

func (c confinedFS) Open(name string) (fs.File, error) {
	slashed := filepath.ToSlash(name)
	if _, ok := containedPath(c.root, slashed); !ok {
		return nil, &fs.PathError{Op: "open", Path: name, Err: fs.ErrPermission}
	}
	return c.fsys.Open(slashed)
}

type xmlExpectations struct {
	Skip  map[string]string `json:"skip"`
	XFail map[string]string `json:"xfail"`
}

func loadXMLExpectations(t *testing.T) xmlExpectations {
	t.Helper()
	p := os.Getenv("XML_EXPECTATIONS")
	if p == "" {
		p = filepath.Join(harness.RepoRoot(t), "expectations", "xml.json")
	}
	data, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("read expectations %s: %v", p, err)
	}
	var exp xmlExpectations
	if err := json.Unmarshal(data, &exp); err != nil {
		t.Fatalf("parse expectations %s: %v", p, err)
	}
	return exp
}

// gatedReason returns a non-empty structural-skip reason when a case is outside
// the suite's live scope: XML 1.1 / Namespaces 1.1 (gated off), or a test tagged
// for XML 1.0 editions that exclude the edition helium implements.
func gatedReason(c xmlCase) string {
	if !xml11Supported && (c.Version == "1.1" || c.Recommendation == "XML1.1" || c.Recommendation == "NS1.1") {
		return "XML 1.1 / Namespaces 1.1 gated off (helium targets XML 1.0)"
	}
	if c.Edition != "" && !editionApplies(c.Edition) {
		return "test applies to XML 1.0 edition(s) " + c.Edition + ", not the " + targetEdition + "th edition helium implements"
	}
	return ""
}

// editionApplies reports whether targetEdition is in a TEST's space-separated
// EDITION list. An empty list (no EDITION attribute) applies to every edition
// and is handled by the caller.
func editionApplies(edition string) bool {
	for _, e := range strings.Fields(edition) {
		if e == targetEdition {
			return true
		}
	}
	return false
}

func TestXMLW3C(t *testing.T) {
	exp := loadXMLExpectations(t)
	testdataRoot := harness.SourceDir(t, "testdata/xml")
	for _, c := range xmlAllCases {
		c := c
		t.Run(c.ID, func(t *testing.T) {
			if reason := gatedReason(c); reason != "" {
				t.Skip(reason)
			}
			if reason := exp.Skip[c.ID]; reason != "" {
				t.Skip(reason)
			}
			xreason, isXFail := exp.XFail[c.ID]
			o := &caseOutcome{t: t, xfail: isXFail}
			runXMLCase(t, o, testdataRoot, c)
			if !isXFail {
				return
			}
			// Expected-failure case: it passes the suite when it fails the
			// conformance check (the known gap), and fails loudly when it
			// unexpectedly passes — helium was fixed and the entry should be
			// removed from expectations/xml.json.
			if len(o.fails) == 0 {
				t.Errorf("XFAIL %s unexpectedly PASSED — helium now conforms; remove it from expectations xfail (%s)", c.ID, xreason)
				return
			}
			t.Logf("xfail (%s): %s", xreason, strings.Join(o.fails, "; "))
		})
	}
}

// caseOutcome routes a case's conformance-signal assertions. For an ordinary
// case, errorf forwards to t.Errorf. For an xfail case it collects the messages
// so TestXMLW3C can invert them. Infrastructure problems (missing fixtures) stay
// on t directly via t.Skipf and are never inverted.
type caseOutcome struct {
	t     *testing.T
	xfail bool
	fails []string
}

func (o *caseOutcome) errorf(format string, args ...any) {
	if o.xfail {
		o.fails = append(o.fails, fmt.Sprintf(format, args...))
		return
	}
	o.t.Errorf(format, args...)
}

// runXMLCase parses the test document as a validating processor (external DTD +
// entities loaded, DTD validation on for valid/invalid) and checks the parse
// outcome against the test's TYPE:
//
//   - valid   → parse+validate MUST succeed with no error
//   - invalid → a validating processor MUST report an error
//   - not-wf  → every processor MUST report a fatal error
//   - error   → optional; a processor MAY report an error — never fails the case
func runXMLCase(t *testing.T, o *caseOutcome, testdataRoot string, c xmlCase) {
	t.Helper()
	defer func() {
		if r := recover(); r != nil {
			o.errorf("%s: panic: %v", c.ID, r)
		}
	}()

	docPath, ok := containedPath(testdataRoot, c.URI)
	if !ok {
		t.Skipf("%s: URI %q escapes the testdata root", c.ID, c.URI)
	}
	src, err := os.ReadFile(docPath)
	if err != nil {
		if os.IsNotExist(err) {
			t.Skipf("fixtures not fetched; run go run ./cmd/w3cgen fetch xml (missing %s)", c.URI)
		}
		t.Fatalf("%s: read document %s: %v", c.ID, c.URI, err)
	}

	validate := c.Type == "valid" || c.Type == "invalid"
	_, perr := helium.NewParser().
		BaseURI(c.URI).
		BlockXXE(false).
		LoadExternalDTD(true).
		DefaultDTDAttributes(true).
		SubstituteEntities(true).
		ValidateDTD(validate).
		FS(newConfinedFS(testdataRoot)).
		Parse(t.Context(), src)

	switch c.Type {
	case "valid":
		if perr != nil {
			o.errorf("%s: expected valid document to parse, got error: %v", c.ID, perr)
		}
	case "invalid":
		// A validating processor must report an error on a well-formed-but-invalid
		// document. Any non-nil error counts: helium reports DTD validity
		// constraints through varied messages, NOT a single sentinel —
		// post-parse validateDocument failures wrap helium.ErrDTDValidationFailed,
		// but DTD-parse-time VCs (Attribute Default Value Syntactically Correct,
		// No Duplicate Tokens, Unique Element Type Declaration) surface with their
		// own messages and are genuine validity detections. Requiring the sentinel
		// would mislabel those correct rejections as failures. (Verified against
		// the W3C corpus: the sentinel-only check wrongly fails ~25 cases helium
		// correctly rejects.)
		if perr == nil {
			o.errorf("%s: expected a validity error, but the document parsed cleanly", c.ID)
		}
	case "not-wf":
		if perr == nil {
			o.errorf("%s: expected a well-formedness error, but the document parsed cleanly", c.ID)
		}
	case "error":
		// Optional error: a conforming processor may or may not report one.
	default:
		t.Fatalf("%s: unknown test TYPE %q", c.ID, c.Type)
	}
}
