// Code generated by w3cgen; DO NOT EDIT.

package xml_test

import (
	"os"
	"testing"

	"github.com/lestrrat-go/helium-w3c-tests/internal/harness"
)

const w3cSuiteName = "xml"
const w3cDisplayName = "XML Conformance"
const w3cSourceKind = "zip"
const w3cSourceRepo = ""
const w3cSourceURL = "https://www.w3.org/XML/Test/xmlts20130923.zip"
const w3cPinnedCommit = ""
const w3cSourceDir = "sources/xml"
const w3cCatalogPath = "sources/xml/xmlconf/xmlconf.xml"
const w3cCatalogTestSets = 6
const w3cCatalogTestCases = 2585
const w3cRunnableTestCases = 2585
const w3cSkippedTestCases = 0
const w3cExcludedTestCases = 0

func TestXMLW3CManifestAvailable(t *testing.T) {
	t.Parallel()
	sourcePath := harness.SourceDir(t, w3cSourceDir)
	if _, err := os.Stat(sourcePath); err != nil {
		if os.IsNotExist(err) {
			t.Skipf("%s source tree not fetched; run %s", w3cDisplayName, "go run ./cmd/w3cgen fetch xml")
		}
		t.Fatalf("stat %s source tree: %v", w3cDisplayName, err)
	}
	if w3cCatalogPath == "" {
		t.Logf("%s source tree present at %s; no catalog file was found", w3cDisplayName, sourcePath)
		return
	}
	t.Logf("%s catalog %s: %d test sets, %d test cases (%d runnable, %d skipped, %d excluded)", w3cDisplayName, w3cCatalogPath, w3cCatalogTestSets, w3cCatalogTestCases, w3cRunnableTestCases, w3cSkippedTestCases, w3cExcludedTestCases)
}
