// Code generated by w3cgen; DO NOT EDIT.

package xml_test

var xmlOasisCases = []xmlCase{
	{
		ID:   "o-p01pass2",
		Type: "valid",
		URI:  "oasis/p01pass2.xml",
	},
	{
		ID:   "o-p06pass1",
		Type: "valid",
		URI:  "oasis/p06pass1.xml",
	},
	{
		ID:   "o-p07pass1",
		Type: "valid",
		URI:  "oasis/p07pass1.xml",
	},
	{
		ID:        "o-p08pass1",
		Type:      "valid",
		URI:       "oasis/p08pass1.xml",
		Namespace: "no",
	},
	{
		ID:       "o-p09pass1",
		Type:     "valid",
		URI:      "oasis/p09pass1.xml",
		Entities: "parameter",
	},
	{
		ID:   "o-p12pass1",
		Type: "valid",
		URI:  "oasis/p12pass1.xml",
	},
	{
		ID:   "o-p22pass4",
		Type: "valid",
		URI:  "oasis/p22pass4.xml",
	},
	{
		ID:   "o-p22pass5",
		Type: "valid",
		URI:  "oasis/p22pass5.xml",
	},
	{
		ID:   "o-p22pass6",
		Type: "valid",
		URI:  "oasis/p22pass6.xml",
	},
	{
		ID:   "o-p28pass1",
		Type: "valid",
		URI:  "oasis/p28pass1.xml",
	},
	{
		ID:       "o-p28pass3",
		Type:     "valid",
		URI:      "oasis/p28pass3.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p28pass4",
		Type:     "valid",
		URI:      "oasis/p28pass4.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p28pass5",
		Type:     "valid",
		URI:      "oasis/p28pass5.xml",
		Entities: "parameter",
	},
	{
		ID:   "o-p29pass1",
		Type: "valid",
		URI:  "oasis/p29pass1.xml",
	},
	{
		ID:       "o-p30pass1",
		Type:     "valid",
		URI:      "oasis/p30pass1.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p30pass2",
		Type:     "valid",
		URI:      "oasis/p30pass2.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p31pass1",
		Type:     "valid",
		URI:      "oasis/p31pass1.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p31pass2",
		Type:     "valid",
		URI:      "oasis/p31pass2.xml",
		Entities: "parameter",
	},
	{
		ID:   "o-p43pass1",
		Type: "valid",
		URI:  "oasis/p43pass1.xml",
	},
	{
		ID:   "o-p45pass1",
		Type: "valid",
		URI:  "oasis/p45pass1.xml",
	},
	{
		ID:   "o-p46pass1",
		Type: "valid",
		URI:  "oasis/p46pass1.xml",
	},
	{
		ID:   "o-p47pass1",
		Type: "valid",
		URI:  "oasis/p47pass1.xml",
	},
	{
		ID:   "o-p48pass1",
		Type: "valid",
		URI:  "oasis/p48pass1.xml",
	},
	{
		ID:   "o-p49pass1",
		Type: "valid",
		URI:  "oasis/p49pass1.xml",
	},
	{
		ID:   "o-p50pass1",
		Type: "valid",
		URI:  "oasis/p50pass1.xml",
	},
	{
		ID:   "o-p51pass1",
		Type: "valid",
		URI:  "oasis/p51pass1.xml",
	},
	{
		ID:   "o-p52pass1",
		Type: "valid",
		URI:  "oasis/p52pass1.xml",
	},
	{
		ID:   "o-p53pass1",
		Type: "valid",
		URI:  "oasis/p53pass1.xml",
	},
	{
		ID:   "o-p54pass1",
		Type: "valid",
		URI:  "oasis/p54pass1.xml",
	},
	{
		ID:   "o-p55pass1",
		Type: "valid",
		URI:  "oasis/p55pass1.xml",
	},
	{
		ID:   "o-p56pass1",
		Type: "valid",
		URI:  "oasis/p56pass1.xml",
	},
	{
		ID:   "o-p57pass1",
		Type: "valid",
		URI:  "oasis/p57pass1.xml",
	},
	{
		ID:   "o-p58pass1",
		Type: "valid",
		URI:  "oasis/p58pass1.xml",
	},
	{
		ID:   "o-p59pass1",
		Type: "valid",
		URI:  "oasis/p59pass1.xml",
	},
	{
		ID:   "o-p60pass1",
		Type: "valid",
		URI:  "oasis/p60pass1.xml",
	},
	{
		ID:       "o-p61pass1",
		Type:     "valid",
		URI:      "oasis/p61pass1.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p62pass1",
		Type:     "valid",
		URI:      "oasis/p62pass1.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p63pass1",
		Type:     "valid",
		URI:      "oasis/p63pass1.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p64pass1",
		Type:     "valid",
		URI:      "oasis/p64pass1.xml",
		Entities: "parameter",
	},
	{
		ID:   "o-p68pass1",
		Type: "valid",
		URI:  "oasis/p68pass1.xml",
	},
	{
		ID:       "o-p69pass1",
		Type:     "valid",
		URI:      "oasis/p69pass1.xml",
		Entities: "parameter",
	},
	{
		ID:   "o-p70pass1",
		Type: "valid",
		URI:  "oasis/p70pass1.xml",
	},
	{
		ID:   "o-p71pass1",
		Type: "valid",
		URI:  "oasis/p71pass1.xml",
	},
	{
		ID:   "o-p72pass1",
		Type: "valid",
		URI:  "oasis/p72pass1.xml",
	},
	{
		ID:   "o-p73pass1",
		Type: "valid",
		URI:  "oasis/p73pass1.xml",
	},
	{
		ID:   "o-p76pass1",
		Type: "valid",
		URI:  "oasis/p76pass1.xml",
	},
	{
		ID:   "o-p01pass1",
		Type: "invalid",
		URI:  "oasis/p01pass1.xml",
	},
	{
		ID:   "o-p01pass3",
		Type: "invalid",
		URI:  "oasis/p01pass3.xml",
	},
	{
		ID:   "o-p03pass1",
		Type: "invalid",
		URI:  "oasis/p03pass1.xml",
	},
	{
		ID:        "o-p04pass1",
		Type:      "invalid",
		URI:       "oasis/p04pass1.xml",
		Namespace: "no",
	},
	{
		ID:        "o-p05pass1",
		Type:      "invalid",
		URI:       "oasis/p05pass1.xml",
		Namespace: "no",
	},
	{
		ID:   "o-p06fail1",
		Type: "invalid",
		URI:  "oasis/p06fail1.xml",
	},
	{
		ID:   "o-p08fail1",
		Type: "invalid",
		URI:  "oasis/p08fail1.xml",
	},
	{
		ID:   "o-p08fail2",
		Type: "invalid",
		URI:  "oasis/p08fail2.xml",
	},
	{
		ID:   "o-p10pass1",
		Type: "invalid",
		URI:  "oasis/p10pass1.xml",
	},
	{
		ID:   "o-p14pass1",
		Type: "invalid",
		URI:  "oasis/p14pass1.xml",
	},
	{
		ID:   "o-p15pass1",
		Type: "invalid",
		URI:  "oasis/p15pass1.xml",
	},
	{
		ID:   "o-p16pass1",
		Type: "invalid",
		URI:  "oasis/p16pass1.xml",
	},
	{
		ID:   "o-p16pass2",
		Type: "invalid",
		URI:  "oasis/p16pass2.xml",
	},
	{
		ID:   "o-p16pass3",
		Type: "invalid",
		URI:  "oasis/p16pass3.xml",
	},
	{
		ID:   "o-p18pass1",
		Type: "invalid",
		URI:  "oasis/p18pass1.xml",
	},
	{
		ID:   "o-p22pass1",
		Type: "invalid",
		URI:  "oasis/p22pass1.xml",
	},
	{
		ID:   "o-p22pass2",
		Type: "invalid",
		URI:  "oasis/p22pass2.xml",
	},
	{
		ID:   "o-p22pass3",
		Type: "invalid",
		URI:  "oasis/p22pass3.xml",
	},
	{
		ID:   "o-p23pass1",
		Type: "invalid",
		URI:  "oasis/p23pass1.xml",
	},
	{
		ID:   "o-p23pass2",
		Type: "invalid",
		URI:  "oasis/p23pass2.xml",
	},
	{
		ID:   "o-p23pass3",
		Type: "invalid",
		URI:  "oasis/p23pass3.xml",
	},
	{
		ID:   "o-p23pass4",
		Type: "invalid",
		URI:  "oasis/p23pass4.xml",
	},
	{
		ID:   "o-p24pass1",
		Type: "invalid",
		URI:  "oasis/p24pass1.xml",
	},
	{
		ID:   "o-p24pass2",
		Type: "invalid",
		URI:  "oasis/p24pass2.xml",
	},
	{
		ID:   "o-p24pass3",
		Type: "invalid",
		URI:  "oasis/p24pass3.xml",
	},
	{
		ID:   "o-p24pass4",
		Type: "invalid",
		URI:  "oasis/p24pass4.xml",
	},
	{
		ID:   "o-p25pass1",
		Type: "invalid",
		URI:  "oasis/p25pass1.xml",
	},
	{
		ID:   "o-p25pass2",
		Type: "invalid",
		URI:  "oasis/p25pass2.xml",
	},
	{
		ID:   "o-p26pass1",
		Type: "invalid",
		URI:  "oasis/p26pass1.xml",
	},
	{
		ID:   "o-p27pass1",
		Type: "invalid",
		URI:  "oasis/p27pass1.xml",
	},
	{
		ID:   "o-p27pass2",
		Type: "invalid",
		URI:  "oasis/p27pass2.xml",
	},
	{
		ID:   "o-p27pass3",
		Type: "invalid",
		URI:  "oasis/p27pass3.xml",
	},
	{
		ID:   "o-p27pass4",
		Type: "invalid",
		URI:  "oasis/p27pass4.xml",
	},
	{
		ID:   "o-p32pass1",
		Type: "invalid",
		URI:  "oasis/p32pass1.xml",
	},
	{
		ID:   "o-p32pass2",
		Type: "invalid",
		URI:  "oasis/p32pass2.xml",
	},
	{
		ID:   "o-p39pass1",
		Type: "invalid",
		URI:  "oasis/p39pass1.xml",
	},
	{
		ID:   "o-p39pass2",
		Type: "invalid",
		URI:  "oasis/p39pass2.xml",
	},
	{
		ID:   "o-p40pass1",
		Type: "invalid",
		URI:  "oasis/p40pass1.xml",
	},
	{
		ID:   "o-p40pass2",
		Type: "invalid",
		URI:  "oasis/p40pass2.xml",
	},
	{
		ID:   "o-p40pass3",
		Type: "invalid",
		URI:  "oasis/p40pass3.xml",
	},
	{
		ID:   "o-p40pass4",
		Type: "invalid",
		URI:  "oasis/p40pass4.xml",
	},
	{
		ID:   "o-p41pass1",
		Type: "invalid",
		URI:  "oasis/p41pass1.xml",
	},
	{
		ID:   "o-p41pass2",
		Type: "invalid",
		URI:  "oasis/p41pass2.xml",
	},
	{
		ID:   "o-p42pass1",
		Type: "invalid",
		URI:  "oasis/p42pass1.xml",
	},
	{
		ID:   "o-p42pass2",
		Type: "invalid",
		URI:  "oasis/p42pass2.xml",
	},
	{
		ID:   "o-p44pass1",
		Type: "invalid",
		URI:  "oasis/p44pass1.xml",
	},
	{
		ID:   "o-p44pass2",
		Type: "invalid",
		URI:  "oasis/p44pass2.xml",
	},
	{
		ID:   "o-p44pass3",
		Type: "invalid",
		URI:  "oasis/p44pass3.xml",
	},
	{
		ID:   "o-p44pass4",
		Type: "invalid",
		URI:  "oasis/p44pass4.xml",
	},
	{
		ID:   "o-p44pass5",
		Type: "invalid",
		URI:  "oasis/p44pass5.xml",
	},
	{
		ID:   "o-p66pass1",
		Type: "invalid",
		URI:  "oasis/p66pass1.xml",
	},
	{
		ID:   "o-p74pass1",
		Type: "invalid",
		URI:  "oasis/p74pass1.xml",
	},
	{
		ID:   "o-p75pass1",
		Type: "invalid",
		URI:  "oasis/p75pass1.xml",
	},
	{
		ID:   "o-e2",
		Type: "invalid",
		URI:  "oasis/e2.xml",
	},
	{
		ID:   "o-p01fail1",
		Type: "not-wf",
		URI:  "oasis/p01fail1.xml",
	},
	{
		ID:   "o-p01fail2",
		Type: "not-wf",
		URI:  "oasis/p01fail2.xml",
	},
	{
		ID:   "o-p01fail3",
		Type: "not-wf",
		URI:  "oasis/p01fail3.xml",
	},
	{
		ID:   "o-p01fail4",
		Type: "not-wf",
		URI:  "oasis/p01fail4.xml",
	},
	{
		ID:   "o-p02fail1",
		Type: "not-wf",
		URI:  "oasis/p02fail1.xml",
	},
	{
		ID:   "o-p02fail10",
		Type: "not-wf",
		URI:  "oasis/p02fail10.xml",
	},
	{
		ID:   "o-p02fail11",
		Type: "not-wf",
		URI:  "oasis/p02fail11.xml",
	},
	{
		ID:   "o-p02fail12",
		Type: "not-wf",
		URI:  "oasis/p02fail12.xml",
	},
	{
		ID:   "o-p02fail13",
		Type: "not-wf",
		URI:  "oasis/p02fail13.xml",
	},
	{
		ID:   "o-p02fail14",
		Type: "not-wf",
		URI:  "oasis/p02fail14.xml",
	},
	{
		ID:   "o-p02fail15",
		Type: "not-wf",
		URI:  "oasis/p02fail15.xml",
	},
	{
		ID:   "o-p02fail16",
		Type: "not-wf",
		URI:  "oasis/p02fail16.xml",
	},
	{
		ID:   "o-p02fail17",
		Type: "not-wf",
		URI:  "oasis/p02fail17.xml",
	},
	{
		ID:   "o-p02fail18",
		Type: "not-wf",
		URI:  "oasis/p02fail18.xml",
	},
	{
		ID:   "o-p02fail19",
		Type: "not-wf",
		URI:  "oasis/p02fail19.xml",
	},
	{
		ID:   "o-p02fail2",
		Type: "not-wf",
		URI:  "oasis/p02fail2.xml",
	},
	{
		ID:   "o-p02fail20",
		Type: "not-wf",
		URI:  "oasis/p02fail20.xml",
	},
	{
		ID:   "o-p02fail21",
		Type: "not-wf",
		URI:  "oasis/p02fail21.xml",
	},
	{
		ID:   "o-p02fail22",
		Type: "not-wf",
		URI:  "oasis/p02fail22.xml",
	},
	{
		ID:   "o-p02fail23",
		Type: "not-wf",
		URI:  "oasis/p02fail23.xml",
	},
	{
		ID:   "o-p02fail24",
		Type: "not-wf",
		URI:  "oasis/p02fail24.xml",
	},
	{
		ID:   "o-p02fail25",
		Type: "not-wf",
		URI:  "oasis/p02fail25.xml",
	},
	{
		ID:   "o-p02fail26",
		Type: "not-wf",
		URI:  "oasis/p02fail26.xml",
	},
	{
		ID:   "o-p02fail27",
		Type: "not-wf",
		URI:  "oasis/p02fail27.xml",
	},
	{
		ID:   "o-p02fail28",
		Type: "not-wf",
		URI:  "oasis/p02fail28.xml",
	},
	{
		ID:   "o-p02fail29",
		Type: "not-wf",
		URI:  "oasis/p02fail29.xml",
	},
	{
		ID:   "o-p02fail3",
		Type: "not-wf",
		URI:  "oasis/p02fail3.xml",
	},
	{
		ID:   "o-p02fail30",
		Type: "not-wf",
		URI:  "oasis/p02fail30.xml",
	},
	{
		ID:   "o-p02fail31",
		Type: "not-wf",
		URI:  "oasis/p02fail31.xml",
	},
	{
		ID:   "o-p02fail4",
		Type: "not-wf",
		URI:  "oasis/p02fail4.xml",
	},
	{
		ID:   "o-p02fail5",
		Type: "not-wf",
		URI:  "oasis/p02fail5.xml",
	},
	{
		ID:   "o-p02fail6",
		Type: "not-wf",
		URI:  "oasis/p02fail6.xml",
	},
	{
		ID:   "o-p02fail7",
		Type: "not-wf",
		URI:  "oasis/p02fail7.xml",
	},
	{
		ID:   "o-p02fail8",
		Type: "not-wf",
		URI:  "oasis/p02fail8.xml",
	},
	{
		ID:   "o-p02fail9",
		Type: "not-wf",
		URI:  "oasis/p02fail9.xml",
	},
	{
		ID:   "o-p03fail1",
		Type: "not-wf",
		URI:  "oasis/p03fail1.xml",
	},
	{
		ID:   "o-p03fail10",
		Type: "not-wf",
		URI:  "oasis/p03fail10.xml",
	},
	{
		ID:   "o-p03fail11",
		Type: "not-wf",
		URI:  "oasis/p03fail11.xml",
	},
	{
		ID:   "o-p03fail12",
		Type: "not-wf",
		URI:  "oasis/p03fail12.xml",
	},
	{
		ID:   "o-p03fail13",
		Type: "not-wf",
		URI:  "oasis/p03fail13.xml",
	},
	{
		ID:   "o-p03fail14",
		Type: "not-wf",
		URI:  "oasis/p03fail14.xml",
	},
	{
		ID:   "o-p03fail15",
		Type: "not-wf",
		URI:  "oasis/p03fail15.xml",
	},
	{
		ID:   "o-p03fail16",
		Type: "not-wf",
		URI:  "oasis/p03fail16.xml",
	},
	{
		ID:   "o-p03fail17",
		Type: "not-wf",
		URI:  "oasis/p03fail17.xml",
	},
	{
		ID:   "o-p03fail18",
		Type: "not-wf",
		URI:  "oasis/p03fail18.xml",
	},
	{
		ID:   "o-p03fail19",
		Type: "not-wf",
		URI:  "oasis/p03fail19.xml",
	},
	{
		ID:   "o-p03fail2",
		Type: "not-wf",
		URI:  "oasis/p03fail2.xml",
	},
	{
		ID:   "o-p03fail20",
		Type: "not-wf",
		URI:  "oasis/p03fail20.xml",
	},
	{
		ID:   "o-p03fail21",
		Type: "not-wf",
		URI:  "oasis/p03fail21.xml",
	},
	{
		ID:   "o-p03fail22",
		Type: "not-wf",
		URI:  "oasis/p03fail22.xml",
	},
	{
		ID:   "o-p03fail23",
		Type: "not-wf",
		URI:  "oasis/p03fail23.xml",
	},
	{
		ID:   "o-p03fail24",
		Type: "not-wf",
		URI:  "oasis/p03fail24.xml",
	},
	{
		ID:   "o-p03fail25",
		Type: "not-wf",
		URI:  "oasis/p03fail25.xml",
	},
	{
		ID:   "o-p03fail26",
		Type: "not-wf",
		URI:  "oasis/p03fail26.xml",
	},
	{
		ID:   "o-p03fail27",
		Type: "not-wf",
		URI:  "oasis/p03fail27.xml",
	},
	{
		ID:   "o-p03fail28",
		Type: "not-wf",
		URI:  "oasis/p03fail28.xml",
	},
	{
		ID:   "o-p03fail29",
		Type: "not-wf",
		URI:  "oasis/p03fail29.xml",
	},
	{
		ID:   "o-p03fail3",
		Type: "not-wf",
		URI:  "oasis/p03fail3.xml",
	},
	{
		ID:   "o-p03fail4",
		Type: "not-wf",
		URI:  "oasis/p03fail4.xml",
	},
	{
		ID:   "o-p03fail5",
		Type: "not-wf",
		URI:  "oasis/p03fail5.xml",
	},
	{
		ID:   "o-p03fail7",
		Type: "not-wf",
		URI:  "oasis/p03fail7.xml",
	},
	{
		ID:   "o-p03fail8",
		Type: "not-wf",
		URI:  "oasis/p03fail8.xml",
	},
	{
		ID:   "o-p03fail9",
		Type: "not-wf",
		URI:  "oasis/p03fail9.xml",
	},
	{
		ID:   "o-p04fail1",
		Type: "not-wf",
		URI:  "oasis/p04fail1.xml",
	},
	{
		ID:   "o-p04fail2",
		Type: "not-wf",
		URI:  "oasis/p04fail2.xml",
	},
	{
		ID:   "o-p04fail3",
		Type: "not-wf",
		URI:  "oasis/p04fail3.xml",
	},
	{
		ID:   "o-p05fail1",
		Type: "not-wf",
		URI:  "oasis/p05fail1.xml",
	},
	{
		ID:   "o-p05fail2",
		Type: "not-wf",
		URI:  "oasis/p05fail2.xml",
	},
	{
		ID:   "o-p05fail3",
		Type: "not-wf",
		URI:  "oasis/p05fail3.xml",
	},
	{
		ID:   "o-p05fail4",
		Type: "not-wf",
		URI:  "oasis/p05fail4.xml",
	},
	{
		ID:   "o-p05fail5",
		Type: "not-wf",
		URI:  "oasis/p05fail5.xml",
	},
	{
		ID:       "o-p09fail1",
		Type:     "not-wf",
		URI:      "oasis/p09fail1.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p09fail2",
		Type:     "not-wf",
		URI:      "oasis/p09fail2.xml",
		Entities: "parameter",
	},
	{
		ID:   "o-p09fail3",
		Type: "not-wf",
		URI:  "oasis/p09fail3.xml",
	},
	{
		ID:   "o-p09fail4",
		Type: "not-wf",
		URI:  "oasis/p09fail4.xml",
	},
	{
		ID:   "o-p09fail5",
		Type: "not-wf",
		URI:  "oasis/p09fail5.xml",
	},
	{
		ID:   "o-p10fail1",
		Type: "not-wf",
		URI:  "oasis/p10fail1.xml",
	},
	{
		ID:   "o-p10fail2",
		Type: "not-wf",
		URI:  "oasis/p10fail2.xml",
	},
	{
		ID:   "o-p10fail3",
		Type: "not-wf",
		URI:  "oasis/p10fail3.xml",
	},
	{
		ID:   "o-p11fail1",
		Type: "not-wf",
		URI:  "oasis/p11fail1.xml",
	},
	{
		ID:   "o-p11fail2",
		Type: "not-wf",
		URI:  "oasis/p11fail2.xml",
	},
	{
		ID:   "o-p12fail1",
		Type: "not-wf",
		URI:  "oasis/p12fail1.xml",
	},
	{
		ID:   "o-p12fail2",
		Type: "not-wf",
		URI:  "oasis/p12fail2.xml",
	},
	{
		ID:   "o-p12fail3",
		Type: "not-wf",
		URI:  "oasis/p12fail3.xml",
	},
	{
		ID:   "o-p12fail4",
		Type: "not-wf",
		URI:  "oasis/p12fail4.xml",
	},
	{
		ID:   "o-p12fail5",
		Type: "not-wf",
		URI:  "oasis/p12fail5.xml",
	},
	{
		ID:   "o-p12fail6",
		Type: "not-wf",
		URI:  "oasis/p12fail6.xml",
	},
	{
		ID:   "o-p12fail7",
		Type: "not-wf",
		URI:  "oasis/p12fail7.xml",
	},
	{
		ID:   "o-p14fail1",
		Type: "not-wf",
		URI:  "oasis/p14fail1.xml",
	},
	{
		ID:   "o-p14fail2",
		Type: "not-wf",
		URI:  "oasis/p14fail2.xml",
	},
	{
		ID:   "o-p14fail3",
		Type: "not-wf",
		URI:  "oasis/p14fail3.xml",
	},
	{
		ID:   "o-p15fail1",
		Type: "not-wf",
		URI:  "oasis/p15fail1.xml",
	},
	{
		ID:   "o-p15fail2",
		Type: "not-wf",
		URI:  "oasis/p15fail2.xml",
	},
	{
		ID:   "o-p15fail3",
		Type: "not-wf",
		URI:  "oasis/p15fail3.xml",
	},
	{
		ID:   "o-p16fail1",
		Type: "not-wf",
		URI:  "oasis/p16fail1.xml",
	},
	{
		ID:   "o-p16fail2",
		Type: "not-wf",
		URI:  "oasis/p16fail2.xml",
	},
	{
		ID:   "o-p16fail3",
		Type: "not-wf",
		URI:  "oasis/p16fail3.xml",
	},
	{
		ID:   "o-p18fail1",
		Type: "not-wf",
		URI:  "oasis/p18fail1.xml",
	},
	{
		ID:   "o-p18fail2",
		Type: "not-wf",
		URI:  "oasis/p18fail2.xml",
	},
	{
		ID:   "o-p18fail3",
		Type: "not-wf",
		URI:  "oasis/p18fail3.xml",
	},
	{
		ID:   "o-p22fail1",
		Type: "not-wf",
		URI:  "oasis/p22fail1.xml",
	},
	{
		ID:   "o-p22fail2",
		Type: "not-wf",
		URI:  "oasis/p22fail2.xml",
	},
	{
		ID:   "o-p23fail1",
		Type: "not-wf",
		URI:  "oasis/p23fail1.xml",
	},
	{
		ID:   "o-p23fail2",
		Type: "not-wf",
		URI:  "oasis/p23fail2.xml",
	},
	{
		ID:   "o-p23fail3",
		Type: "not-wf",
		URI:  "oasis/p23fail3.xml",
	},
	{
		ID:   "o-p23fail4",
		Type: "not-wf",
		URI:  "oasis/p23fail4.xml",
	},
	{
		ID:   "o-p23fail5",
		Type: "not-wf",
		URI:  "oasis/p23fail5.xml",
	},
	{
		ID:   "o-p24fail1",
		Type: "not-wf",
		URI:  "oasis/p24fail1.xml",
	},
	{
		ID:   "o-p24fail2",
		Type: "not-wf",
		URI:  "oasis/p24fail2.xml",
	},
	{
		ID:   "o-p25fail1",
		Type: "not-wf",
		URI:  "oasis/p25fail1.xml",
	},
	{
		ID:   "o-p26fail1",
		Type: "not-wf",
		URI:  "oasis/p26fail1.xml",
	},
	{
		ID:   "o-p26fail2",
		Type: "not-wf",
		URI:  "oasis/p26fail2.xml",
	},
	{
		ID:   "o-p27fail1",
		Type: "not-wf",
		URI:  "oasis/p27fail1.xml",
	},
	{
		ID:   "o-p28fail1",
		Type: "not-wf",
		URI:  "oasis/p28fail1.xml",
	},
	{
		ID:   "o-p29fail1",
		Type: "not-wf",
		URI:  "oasis/p29fail1.xml",
	},
	{
		ID:       "o-p30fail1",
		Type:     "not-wf",
		URI:      "oasis/p30fail1.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p31fail1",
		Type:     "not-wf",
		URI:      "oasis/p31fail1.xml",
		Entities: "parameter",
	},
	{
		ID:   "o-p32fail1",
		Type: "not-wf",
		URI:  "oasis/p32fail1.xml",
	},
	{
		ID:   "o-p32fail2",
		Type: "not-wf",
		URI:  "oasis/p32fail2.xml",
	},
	{
		ID:   "o-p32fail3",
		Type: "not-wf",
		URI:  "oasis/p32fail3.xml",
	},
	{
		ID:   "o-p32fail4",
		Type: "not-wf",
		URI:  "oasis/p32fail4.xml",
	},
	{
		ID:   "o-p32fail5",
		Type: "not-wf",
		URI:  "oasis/p32fail5.xml",
	},
	{
		ID:   "o-p39fail1",
		Type: "not-wf",
		URI:  "oasis/p39fail1.xml",
	},
	{
		ID:   "o-p39fail2",
		Type: "not-wf",
		URI:  "oasis/p39fail2.xml",
	},
	{
		ID:   "o-p39fail3",
		Type: "not-wf",
		URI:  "oasis/p39fail3.xml",
	},
	{
		ID:   "o-p39fail4",
		Type: "not-wf",
		URI:  "oasis/p39fail4.xml",
	},
	{
		ID:   "o-p39fail5",
		Type: "not-wf",
		URI:  "oasis/p39fail5.xml",
	},
	{
		ID:   "o-p40fail1",
		Type: "not-wf",
		URI:  "oasis/p40fail1.xml",
	},
	{
		ID:   "o-p40fail2",
		Type: "not-wf",
		URI:  "oasis/p40fail2.xml",
	},
	{
		ID:   "o-p40fail3",
		Type: "not-wf",
		URI:  "oasis/p40fail3.xml",
	},
	{
		ID:   "o-p40fail4",
		Type: "not-wf",
		URI:  "oasis/p40fail4.xml",
	},
	{
		ID:   "o-p41fail1",
		Type: "not-wf",
		URI:  "oasis/p41fail1.xml",
	},
	{
		ID:   "o-p41fail2",
		Type: "not-wf",
		URI:  "oasis/p41fail2.xml",
	},
	{
		ID:   "o-p41fail3",
		Type: "not-wf",
		URI:  "oasis/p41fail3.xml",
	},
	{
		ID:   "o-p42fail1",
		Type: "not-wf",
		URI:  "oasis/p42fail1.xml",
	},
	{
		ID:   "o-p42fail2",
		Type: "not-wf",
		URI:  "oasis/p42fail2.xml",
	},
	{
		ID:   "o-p42fail3",
		Type: "not-wf",
		URI:  "oasis/p42fail3.xml",
	},
	{
		ID:   "o-p43fail1",
		Type: "not-wf",
		URI:  "oasis/p43fail1.xml",
	},
	{
		ID:   "o-p43fail2",
		Type: "not-wf",
		URI:  "oasis/p43fail2.xml",
	},
	{
		ID:   "o-p43fail3",
		Type: "not-wf",
		URI:  "oasis/p43fail3.xml",
	},
	{
		ID:   "o-p44fail1",
		Type: "not-wf",
		URI:  "oasis/p44fail1.xml",
	},
	{
		ID:   "o-p44fail2",
		Type: "not-wf",
		URI:  "oasis/p44fail2.xml",
	},
	{
		ID:   "o-p44fail3",
		Type: "not-wf",
		URI:  "oasis/p44fail3.xml",
	},
	{
		ID:   "o-p44fail4",
		Type: "not-wf",
		URI:  "oasis/p44fail4.xml",
	},
	{
		ID:   "o-p44fail5",
		Type: "not-wf",
		URI:  "oasis/p44fail5.xml",
	},
	{
		ID:   "o-p45fail1",
		Type: "not-wf",
		URI:  "oasis/p45fail1.xml",
	},
	{
		ID:   "o-p45fail2",
		Type: "not-wf",
		URI:  "oasis/p45fail2.xml",
	},
	{
		ID:   "o-p45fail3",
		Type: "not-wf",
		URI:  "oasis/p45fail3.xml",
	},
	{
		ID:   "o-p45fail4",
		Type: "not-wf",
		URI:  "oasis/p45fail4.xml",
	},
	{
		ID:   "o-p46fail1",
		Type: "not-wf",
		URI:  "oasis/p46fail1.xml",
	},
	{
		ID:   "o-p46fail2",
		Type: "not-wf",
		URI:  "oasis/p46fail2.xml",
	},
	{
		ID:   "o-p46fail3",
		Type: "not-wf",
		URI:  "oasis/p46fail3.xml",
	},
	{
		ID:   "o-p46fail4",
		Type: "not-wf",
		URI:  "oasis/p46fail4.xml",
	},
	{
		ID:   "o-p46fail5",
		Type: "not-wf",
		URI:  "oasis/p46fail5.xml",
	},
	{
		ID:   "o-p46fail6",
		Type: "not-wf",
		URI:  "oasis/p46fail6.xml",
	},
	{
		ID:   "o-p47fail1",
		Type: "not-wf",
		URI:  "oasis/p47fail1.xml",
	},
	{
		ID:   "o-p47fail2",
		Type: "not-wf",
		URI:  "oasis/p47fail2.xml",
	},
	{
		ID:   "o-p47fail3",
		Type: "not-wf",
		URI:  "oasis/p47fail3.xml",
	},
	{
		ID:   "o-p47fail4",
		Type: "not-wf",
		URI:  "oasis/p47fail4.xml",
	},
	{
		ID:   "o-p48fail1",
		Type: "not-wf",
		URI:  "oasis/p48fail1.xml",
	},
	{
		ID:   "o-p48fail2",
		Type: "not-wf",
		URI:  "oasis/p48fail2.xml",
	},
	{
		ID:   "o-p49fail1",
		Type: "not-wf",
		URI:  "oasis/p49fail1.xml",
	},
	{
		ID:   "o-p50fail1",
		Type: "not-wf",
		URI:  "oasis/p50fail1.xml",
	},
	{
		ID:   "o-p51fail1",
		Type: "not-wf",
		URI:  "oasis/p51fail1.xml",
	},
	{
		ID:   "o-p51fail2",
		Type: "not-wf",
		URI:  "oasis/p51fail2.xml",
	},
	{
		ID:   "o-p51fail3",
		Type: "not-wf",
		URI:  "oasis/p51fail3.xml",
	},
	{
		ID:   "o-p51fail4",
		Type: "not-wf",
		URI:  "oasis/p51fail4.xml",
	},
	{
		ID:   "o-p51fail5",
		Type: "not-wf",
		URI:  "oasis/p51fail5.xml",
	},
	{
		ID:   "o-p51fail6",
		Type: "not-wf",
		URI:  "oasis/p51fail6.xml",
	},
	{
		ID:   "o-p51fail7",
		Type: "not-wf",
		URI:  "oasis/p51fail7.xml",
	},
	{
		ID:   "o-p52fail1",
		Type: "not-wf",
		URI:  "oasis/p52fail1.xml",
	},
	{
		ID:   "o-p52fail2",
		Type: "not-wf",
		URI:  "oasis/p52fail2.xml",
	},
	{
		ID:   "o-p53fail1",
		Type: "not-wf",
		URI:  "oasis/p53fail1.xml",
	},
	{
		ID:   "o-p53fail2",
		Type: "not-wf",
		URI:  "oasis/p53fail2.xml",
	},
	{
		ID:   "o-p53fail3",
		Type: "not-wf",
		URI:  "oasis/p53fail3.xml",
	},
	{
		ID:   "o-p53fail4",
		Type: "not-wf",
		URI:  "oasis/p53fail4.xml",
	},
	{
		ID:   "o-p53fail5",
		Type: "not-wf",
		URI:  "oasis/p53fail5.xml",
	},
	{
		ID:   "o-p54fail1",
		Type: "not-wf",
		URI:  "oasis/p54fail1.xml",
	},
	{
		ID:   "o-p55fail1",
		Type: "not-wf",
		URI:  "oasis/p55fail1.xml",
	},
	{
		ID:   "o-p56fail1",
		Type: "not-wf",
		URI:  "oasis/p56fail1.xml",
	},
	{
		ID:   "o-p56fail2",
		Type: "not-wf",
		URI:  "oasis/p56fail2.xml",
	},
	{
		ID:   "o-p56fail3",
		Type: "not-wf",
		URI:  "oasis/p56fail3.xml",
	},
	{
		ID:   "o-p56fail4",
		Type: "not-wf",
		URI:  "oasis/p56fail4.xml",
	},
	{
		ID:   "o-p56fail5",
		Type: "not-wf",
		URI:  "oasis/p56fail5.xml",
	},
	{
		ID:   "o-p57fail1",
		Type: "not-wf",
		URI:  "oasis/p57fail1.xml",
	},
	{
		ID:   "o-p58fail1",
		Type: "not-wf",
		URI:  "oasis/p58fail1.xml",
	},
	{
		ID:   "o-p58fail2",
		Type: "not-wf",
		URI:  "oasis/p58fail2.xml",
	},
	{
		ID:   "o-p58fail3",
		Type: "not-wf",
		URI:  "oasis/p58fail3.xml",
	},
	{
		ID:   "o-p58fail4",
		Type: "not-wf",
		URI:  "oasis/p58fail4.xml",
	},
	{
		ID:   "o-p58fail5",
		Type: "not-wf",
		URI:  "oasis/p58fail5.xml",
	},
	{
		ID:   "o-p58fail6",
		Type: "not-wf",
		URI:  "oasis/p58fail6.xml",
	},
	{
		ID:   "o-p58fail7",
		Type: "not-wf",
		URI:  "oasis/p58fail7.xml",
	},
	{
		ID:   "o-p58fail8",
		Type: "not-wf",
		URI:  "oasis/p58fail8.xml",
	},
	{
		ID:   "o-p59fail1",
		Type: "not-wf",
		URI:  "oasis/p59fail1.xml",
	},
	{
		ID:   "o-p59fail2",
		Type: "not-wf",
		URI:  "oasis/p59fail2.xml",
	},
	{
		ID:   "o-p59fail3",
		Type: "not-wf",
		URI:  "oasis/p59fail3.xml",
	},
	{
		ID:   "o-p60fail1",
		Type: "not-wf",
		URI:  "oasis/p60fail1.xml",
	},
	{
		ID:   "o-p60fail2",
		Type: "not-wf",
		URI:  "oasis/p60fail2.xml",
	},
	{
		ID:   "o-p60fail3",
		Type: "not-wf",
		URI:  "oasis/p60fail3.xml",
	},
	{
		ID:   "o-p60fail4",
		Type: "not-wf",
		URI:  "oasis/p60fail4.xml",
	},
	{
		ID:   "o-p60fail5",
		Type: "not-wf",
		URI:  "oasis/p60fail5.xml",
	},
	{
		ID:       "o-p61fail1",
		Type:     "not-wf",
		URI:      "oasis/p61fail1.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p62fail1",
		Type:     "not-wf",
		URI:      "oasis/p62fail1.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p62fail2",
		Type:     "not-wf",
		URI:      "oasis/p62fail2.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p63fail1",
		Type:     "not-wf",
		URI:      "oasis/p63fail1.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p63fail2",
		Type:     "not-wf",
		URI:      "oasis/p63fail2.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p64fail1",
		Type:     "not-wf",
		URI:      "oasis/p64fail1.xml",
		Entities: "parameter",
	},
	{
		ID:       "o-p64fail2",
		Type:     "not-wf",
		URI:      "oasis/p64fail2.xml",
		Entities: "parameter",
	},
	{
		ID:   "o-p66fail1",
		Type: "not-wf",
		URI:  "oasis/p66fail1.xml",
	},
	{
		ID:   "o-p66fail2",
		Type: "not-wf",
		URI:  "oasis/p66fail2.xml",
	},
	{
		ID:   "o-p66fail3",
		Type: "not-wf",
		URI:  "oasis/p66fail3.xml",
	},
	{
		ID:   "o-p66fail4",
		Type: "not-wf",
		URI:  "oasis/p66fail4.xml",
	},
	{
		ID:   "o-p66fail5",
		Type: "not-wf",
		URI:  "oasis/p66fail5.xml",
	},
	{
		ID:   "o-p66fail6",
		Type: "not-wf",
		URI:  "oasis/p66fail6.xml",
	},
	{
		ID:   "o-p68fail1",
		Type: "not-wf",
		URI:  "oasis/p68fail1.xml",
	},
	{
		ID:   "o-p68fail2",
		Type: "not-wf",
		URI:  "oasis/p68fail2.xml",
	},
	{
		ID:   "o-p68fail3",
		Type: "not-wf",
		URI:  "oasis/p68fail3.xml",
	},
	{
		ID:   "o-p69fail1",
		Type: "not-wf",
		URI:  "oasis/p69fail1.xml",
	},
	{
		ID:   "o-p69fail2",
		Type: "not-wf",
		URI:  "oasis/p69fail2.xml",
	},
	{
		ID:   "o-p69fail3",
		Type: "not-wf",
		URI:  "oasis/p69fail3.xml",
	},
	{
		ID:   "o-p70fail1",
		Type: "not-wf",
		URI:  "oasis/p70fail1.xml",
	},
	{
		ID:   "o-p71fail1",
		Type: "not-wf",
		URI:  "oasis/p71fail1.xml",
	},
	{
		ID:   "o-p71fail2",
		Type: "not-wf",
		URI:  "oasis/p71fail2.xml",
	},
	{
		ID:   "o-p71fail3",
		Type: "not-wf",
		URI:  "oasis/p71fail3.xml",
	},
	{
		ID:   "o-p71fail4",
		Type: "not-wf",
		URI:  "oasis/p71fail4.xml",
	},
	{
		ID:   "o-p72fail1",
		Type: "not-wf",
		URI:  "oasis/p72fail1.xml",
	},
	{
		ID:   "o-p72fail2",
		Type: "not-wf",
		URI:  "oasis/p72fail2.xml",
	},
	{
		ID:   "o-p72fail3",
		Type: "not-wf",
		URI:  "oasis/p72fail3.xml",
	},
	{
		ID:   "o-p72fail4",
		Type: "not-wf",
		URI:  "oasis/p72fail4.xml",
	},
	{
		ID:   "o-p73fail1",
		Type: "not-wf",
		URI:  "oasis/p73fail1.xml",
	},
	{
		ID:   "o-p73fail2",
		Type: "not-wf",
		URI:  "oasis/p73fail2.xml",
	},
	{
		ID:   "o-p73fail3",
		Type: "not-wf",
		URI:  "oasis/p73fail3.xml",
	},
	{
		ID:   "o-p73fail4",
		Type: "not-wf",
		URI:  "oasis/p73fail4.xml",
	},
	{
		ID:   "o-p73fail5",
		Type: "not-wf",
		URI:  "oasis/p73fail5.xml",
	},
	{
		ID:   "o-p74fail1",
		Type: "not-wf",
		URI:  "oasis/p74fail1.xml",
	},
	{
		ID:   "o-p74fail2",
		Type: "not-wf",
		URI:  "oasis/p74fail2.xml",
	},
	{
		ID:   "o-p74fail3",
		Type: "not-wf",
		URI:  "oasis/p74fail3.xml",
	},
	{
		ID:   "o-p75fail1",
		Type: "not-wf",
		URI:  "oasis/p75fail1.xml",
	},
	{
		ID:   "o-p75fail2",
		Type: "not-wf",
		URI:  "oasis/p75fail2.xml",
	},
	{
		ID:   "o-p75fail3",
		Type: "not-wf",
		URI:  "oasis/p75fail3.xml",
	},
	{
		ID:   "o-p75fail4",
		Type: "not-wf",
		URI:  "oasis/p75fail4.xml",
	},
	{
		ID:   "o-p75fail5",
		Type: "not-wf",
		URI:  "oasis/p75fail5.xml",
	},
	{
		ID:   "o-p75fail6",
		Type: "not-wf",
		URI:  "oasis/p75fail6.xml",
	},
	{
		ID:   "o-p76fail1",
		Type: "not-wf",
		URI:  "oasis/p76fail1.xml",
	},
	{
		ID:   "o-p76fail2",
		Type: "not-wf",
		URI:  "oasis/p76fail2.xml",
	},
	{
		ID:   "o-p76fail3",
		Type: "not-wf",
		URI:  "oasis/p76fail3.xml",
	},
	{
		ID:   "o-p76fail4",
		Type: "not-wf",
		URI:  "oasis/p76fail4.xml",
	},
	{
		ID:   "o-p11pass1",
		Type: "error",
		URI:  "oasis/p11pass1.xml",
	},
}

func init() { xmlAllCases = append(xmlAllCases, xmlOasisCases...) }
