package xsd11

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/lestrrat-go/helium-w3c-tests/internal/generator"
)

type Suite struct{}

func New() Suite {
	return Suite{}
}

func (Suite) Name() string {
	return "xsd11"
}

// Fetch clones the upstream suite, then copies the XSD-1.1 fixtures it
// references (every schemaDocument, its transitive schemaLocation includes, and
// every instanceDocument) from sources/xsd11 into testdata/xsd11, preserving the
// suite-root-relative layout so xs:include/import resolve at test time.
func (s Suite) Fetch(ctx context.Context, genCtx generator.Context, suiteLock generator.SuiteLock) error {
	if err := generator.FetchSource(ctx, genCtx.Root, s.Name(), suiteLock); err != nil {
		return err
	}
	return s.populateFixtures(genCtx.Root, suiteLock)
}

func (s Suite) populateFixtures(root string, suiteLock generator.SuiteLock) error {
	sourceRoot := filepath.Join(root, filepath.FromSlash(suiteLock.SourceDir))
	byContributor, _, _, _, err := readCases(sourceRoot)
	if err != nil {
		return err
	}

	rels := map[string]bool{}
	for _, cases := range byContributor {
		for _, c := range cases {
			for _, rel := range c.FixtureRels {
				rels[rel] = true
			}
		}
	}

	destRoot := filepath.Join(root, "testdata", "xsd11")
	sorted := make([]string, 0, len(rels))
	for rel := range rels {
		sorted = append(sorted, rel)
	}
	sort.Strings(sorted)

	for _, rel := range sorted {
		src, err := generator.ContainedPath(sourceRoot, rel)
		if err != nil {
			return fmt.Errorf("resolve fixture %q: %w", rel, err)
		}
		dst, err := generator.ContainedPath(destRoot, rel)
		if err != nil {
			return fmt.Errorf("resolve fixture dest %q: %w", rel, err)
		}
		if err := copyFile(src, dst); err != nil {
			return err
		}
	}
	fmt.Printf("xsd11: copied %d fixtures into testdata/xsd11\n", len(sorted))
	return nil
}

func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return fmt.Errorf("create fixture dir for %s: %w", dst, err)
	}
	in, err := os.Open(src) //nolint:gosec // src is contained under the suite root
	if err != nil {
		return fmt.Errorf("open fixture %s: %w", src, err)
	}
	defer in.Close()
	out, err := os.Create(dst) //nolint:gosec // dst is contained under testdata/xsd11
	if err != nil {
		return fmt.Errorf("create fixture %s: %w", dst, err)
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return fmt.Errorf("copy fixture %s: %w", dst, err)
	}
	if err := out.Close(); err != nil {
		return fmt.Errorf("close fixture %s: %w", dst, err)
	}
	return nil
}

func (s Suite) Generate(ctx context.Context, genCtx generator.Context, suiteLock generator.SuiteLock, mode generator.GenerateMode) error {
	_ = ctx
	sourceRoot := filepath.Join(genCtx.Root, filepath.FromSlash(suiteLock.SourceDir))

	info := generator.CatalogInfo{SourceDir: suiteLock.SourceDir}
	if _, err := os.Stat(sourceRoot); err == nil {
		info.Present = true
		info.CatalogPath = filepath.ToSlash(filepath.Join(suiteLock.SourceDir, "suite.xml"))
	}

	var byContributor map[string][]genCase
	var contributors []string
	if info.Present {
		var setsScanned, groupsOut int
		var err error
		byContributor, contributors, setsScanned, groupsOut, err = readCases(sourceRoot)
		if err != nil {
			return err
		}
		info.TestSetCount = setsScanned
		info.TestCaseCount = groupsOut
		info.RunnableCount = groupsOut
	}

	manifest := generator.ManifestTestSource(generator.ManifestTest{
		PackageName:  "xsd_test",
		TestName:     "TestXSD11W3CManifestAvailable",
		DisplayName:  "XSD 1.1",
		SuiteName:    s.Name(),
		FetchCommand: "go run ./cmd/w3cgen fetch xsd11",
		Lock:         suiteLock,
		Catalog:      info,
	})
	if err := generator.WriteGoFile(filepath.Join(genCtx.Root, "xsd", "xsd11_manifest_gen_test.go"), manifest, mode); err != nil {
		return err
	}

	for _, contributor := range contributors {
		source := casesSource(contributor, byContributor[contributor])
		out := filepath.Join(genCtx.Root, "xsd", "xsd11_"+contributor+"_gen_test.go")
		if err := generator.WriteGoFile(out, source, mode); err != nil {
			return err
		}
	}
	return nil
}

func casesSource(contributor string, cases []genCase) string {
	varName := "xsts" + titleCase(contributor) + "Cases"

	var b strings.Builder
	b.WriteString("// Code generated by w3cgen; DO NOT EDIT.\n\n")
	b.WriteString("package xsd_test\n\n")
	fmt.Fprintf(&b, "var %s = []xstsCase{\n", varName)
	for _, c := range cases {
		b.WriteString("\t{\n")
		fmt.Fprintf(&b, "\t\tID: %s,\n", strconv.Quote(c.ID))
		fmt.Fprintf(&b, "\t\tSchemaRel: %s,\n", strconv.Quote(c.SchemaRel))
		fmt.Fprintf(&b, "\t\tSchemaValid: %t,\n", c.SchemaValid)
		// Emit the full document list only for multi-document schemaTests so
		// single-document cases stay byte-identical to the pre-feature output.
		if len(c.SchemaDocs) > 1 {
			b.WriteString("\t\tSchemaDocs: []string{\n")
			for _, d := range c.SchemaDocs {
				fmt.Fprintf(&b, "\t\t\t%s,\n", strconv.Quote(d))
			}
			b.WriteString("\t\t},\n")
		}
		if len(c.Instances) > 0 {
			b.WriteString("\t\tInstances: []xstsInstance{\n")
			for _, in := range c.Instances {
				fmt.Fprintf(&b, "\t\t\t{Name: %s, Rel: %s, Valid: %t},\n",
					strconv.Quote(in.Name), strconv.Quote(in.Rel), in.Valid)
			}
			b.WriteString("\t\t},\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "func init() { xstsAllCases = append(xstsAllCases, %s...) }\n", varName)
	return b.String()
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
