package xsd11

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/lestrrat-go/helium-w3c-tests/internal/generator"
)

type Suite struct{}

func New() Suite {
	return Suite{}
}

func (Suite) Name() string {
	return "xsd11"
}

func (s Suite) Fetch(ctx context.Context, genCtx generator.Context, suiteLock generator.SuiteLock) error {
	return generator.FetchSource(ctx, genCtx.Root, s.Name(), suiteLock)
}

func (s Suite) Generate(ctx context.Context, genCtx generator.Context, suiteLock generator.SuiteLock, mode generator.GenerateMode) error {
	_ = ctx
	catalog, err := generator.ReadCatalogInfo(genCtx.Root, suiteLock)
	if err != nil {
		return err
	}
	manifest := generator.ManifestTestSource(generator.ManifestTest{
		PackageName:  "xsd_test",
		TestName:     "TestXSD11W3CManifestAvailable",
		DisplayName:  "XSD 1.1",
		SuiteName:    s.Name(),
		FetchCommand: "go run ./cmd/w3cgen fetch xsd11",
		Lock:         suiteLock,
		Catalog:      catalog,
	})
	if err := generator.WriteGoFile(filepath.Join(genCtx.Root, "xsd", "xsd11_manifest_gen_test.go"), manifest, mode); err != nil {
		return err
	}
	return generator.WriteGoFile(filepath.Join(genCtx.Root, "xsd", "xsd11_smoke_gen_test.go"), smokeSource(), mode)
}

func smokeSource() string {
	var b strings.Builder
	b.WriteString("// Code generated by w3cgen; DO NOT EDIT.\n\n")
	b.WriteString("package xsd_test\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"testing\"\n\n")
	b.WriteString("\thelium \"github.com/lestrrat-go/helium\"\n")
	b.WriteString("\t\"github.com/lestrrat-go/helium/xsd\"\n")
	b.WriteString(")\n\n")
	b.WriteString("func TestXSD11SmokeDoublePositiveInfinity(t *testing.T) {\n")
	b.WriteString("\tt.Parallel()\n")
	fmt.Fprintf(&b, "\tschemaXML := %q\n", `<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="value" type="xs:double"/>
</xs:schema>`)
	fmt.Fprintf(&b, "\tinstanceXML := %q\n", `<value>+INF</value>`)
	b.WriteString("\tschemaDoc, err := helium.NewParser().Parse(t.Context(), []byte(schemaXML))\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tt.Fatalf(\"parse schema: %v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tschema, err := xsd.NewCompiler().Label(\"xsd11-smoke.xsd\").Compile(t.Context(), schemaDoc)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tt.Fatalf(\"compile schema: %v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tinstanceDoc, err := helium.NewParser().Parse(t.Context(), []byte(instanceXML))\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tt.Fatalf(\"parse instance: %v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := xsd.NewValidator(schema).Label(\"xsd11-smoke.xml\").Validate(t.Context(), instanceDoc); err != nil {\n")
	b.WriteString("\t\tt.Fatalf(\"validate +INF as xs:double: %v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}
