// Code generated by w3cgen; DO NOT EDIT.

package xmlenc_test

var xmlenc11Cases = []xmlenc11Case{
	{
		ID:   "cipherText__EC-P256__aes128-gcm__kw-aes128__ECDH-ES__ConcatKDF-1",
		File: "cipherText__EC-P256__aes128-gcm__kw-aes128__ECDH-ES__ConcatKDF-1.xml",
	},
	{
		ID:   "cipherText__EC-P256__aes128-gcm__kw-aes128__ECDH-ES__ConcatKDF-4",
		File: "cipherText__EC-P256__aes128-gcm__kw-aes128__ECDH-ES__ConcatKDF-4.xml",
	},
	{
		ID:   "cipherText__EC-P384__aes192-gcm__kw-aes192__ECDH-ES__ConcatKDF-2",
		File: "cipherText__EC-P384__aes192-gcm__kw-aes192__ECDH-ES__ConcatKDF-2.xml",
	},
	{
		ID:   "cipherText__EC-P384__aes192-gcm__kw-aes192__ECDH-ES__ConcatKDF-5",
		File: "cipherText__EC-P384__aes192-gcm__kw-aes192__ECDH-ES__ConcatKDF-5.xml",
	},
	{
		ID:   "cipherText__EC-P521__aes256-gcm__kw-aes256__ECDH-ES__ConcatKDF-3",
		File: "cipherText__EC-P521__aes256-gcm__kw-aes256__ECDH-ES__ConcatKDF-3.xml",
	},
	{
		ID:   "cipherText__EC-P521__aes256-gcm__kw-aes256__ECDH-ES__ConcatKDF-6",
		File: "cipherText__EC-P521__aes256-gcm__kw-aes256__ECDH-ES__ConcatKDF-6.xml",
	},
	{
		ID:      "cipherText__RSA-2048__aes128-gcm__rsa-oaep-mgf1p",
		File:    "cipherText__RSA-2048__aes128-gcm__rsa-oaep-mgf1p.xml",
		KeyFile: "RSA-2048_SHA256WithRSA.p12",
	},
	{
		ID:      "cipherText__RSA-3072__aes192-gcm__rsa-oaep-mgf1p__Sha256",
		File:    "cipherText__RSA-3072__aes192-gcm__rsa-oaep-mgf1p__Sha256.xml",
		KeyFile: "RSA-3072_SHA256WithRSA.p12",
	},
	{
		ID:      "cipherText__RSA-3072__aes256-gcm__rsa-oaep__Sha384-MGF_Sha1",
		File:    "cipherText__RSA-3072__aes256-gcm__rsa-oaep__Sha384-MGF_Sha1.xml",
		KeyFile: "RSA-3072_SHA256WithRSA.p12",
	},
	{
		ID:      "cipherText__RSA-4096__aes256-gcm__rsa-oaep__Sha512-MGF_Sha1_PSource",
		File:    "cipherText__RSA-4096__aes256-gcm__rsa-oaep__Sha512-MGF_Sha1_PSource.xml",
		KeyFile: "RSA-4096_SHA256WithRSA.p12",
	},
}
