package junit

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"
)

// Summary is a per-suite conformance result rollup produced from
// `go test -json` output. It is the durable, human-readable evidence committed
// alongside (or instead of) the full JUnit XML.
type Summary struct {
	Suite   string
	Total   int
	Passed  int
	Skipped int
	Failed  int
	// XFailed counts cases the harness expected to fail (a known, documented gap):
	// the subtest passes because the case fails as its expectations predict, so a
	// plain pass/fail rollup would otherwise hide it inside Passed.
	XFailed int
	// SkipReasons counts skipped cases by their skip message.
	SkipReasons map[string]int
	// XFailReasons counts expected-failure cases by their xfail reason.
	XFailReasons map[string]int
}

// Summarize reads `go test -json` output and rolls up the subtests of
// opt.RootTest (one entry per "<RootTest>/<case>" subtest, matching the JUnit
// conversion) into a Summary. The root test itself and any non-matching test
// are ignored.
func Summarize(r io.Reader, opt Options) (Summary, error) {
	if opt.RootTest == "" {
		return Summary{}, fmt.Errorf("root test is required")
	}
	s := Summary{Suite: opt.SuiteName, SkipReasons: map[string]int{}, XFailReasons: map[string]int{}}

	type rec struct {
		status string
		output []string
	}
	records := map[string]*rec{}
	order := []string{}
	packageFailed := false
	dec := json.NewDecoder(r)
	for {
		var ev event
		if err := dec.Decode(&ev); err != nil {
			if err == io.EOF {
				break
			}
			return Summary{}, err
		}
		if ev.Test == "" {
			// Package-level events: a build failure or a package fail with no
			// case events (e.g. a compile error) must still surface as a failure.
			if ev.Action == "build-fail" || ev.Action == "fail" {
				packageFailed = true
			}
			continue
		}
		if !strings.HasPrefix(ev.Test, opt.RootTest+"/") {
			continue
		}
		rc := records[ev.Test]
		if rc == nil {
			rc = &rec{}
			records[ev.Test] = rc
			order = append(order, ev.Test)
		}
		switch ev.Action {
		case "pass", "fail", "skip":
			rc.status = ev.Action
		case "output":
			rc.output = append(rc.output, ev.Output)
		}
	}

	// Mirror ConvertGoTestJSON: if the test binary never produced any case
	// results but the package failed to build/run, record one synthetic failure
	// so the committed evidence never silently reads as a clean, empty suite.
	if len(order) == 0 && packageFailed {
		s.Failed++
		s.Total++
		return s, nil
	}

	for _, name := range order {
		rc := records[name]
		switch rc.status {
		case "pass":
			if reason, ok := xfailReason(rc.output); ok {
				s.XFailed++
				s.XFailReasons[reason]++
				break
			}
			s.Passed++
		case "fail":
			s.Failed++
		case "skip":
			s.Skipped++
			reason := firstMeaningfulLine(strings.Join(rc.output, ""))
			if reason == "" {
				reason = "(no reason given)"
			}
			s.SkipReasons[reason]++
		default:
			continue // no terminal status recorded; don't count it
		}
		s.Total++
	}
	return s, nil
}

// SummaryMeta is provenance recorded alongside a rendered Summary. The caller
// supplies GeneratedAt so rendering stays a pure function of its inputs.
type SummaryMeta struct {
	DisplayName    string // e.g. "XSLT 3.0"
	UpstreamRepo   string // e.g. "https://github.com/w3c/xslt30-test"
	UpstreamCommit string // pinned suite commit
	HeliumCommit   string // helium (code under test) commit the suite ran against (optional)
	HarnessCommit  string // helium-w3c-tests (harness) commit that produced the run (optional)
	GoVersion      string // Go version/toolchain that ran the suite (optional)
	Mode           string // run mode, e.g. "default" or "slow (HELIUM_SLOW_TESTS=1)" (optional)
	GeneratedAt    string // caller-supplied timestamp (optional)
}

// WriteSummaryMarkdown renders s and meta as a committed conformance-evidence
// report: a provenance header, a totals table, and a skip-reason breakdown
// sorted by descending count then reason.
func WriteSummaryMarkdown(w io.Writer, s Summary, meta SummaryMeta) error {
	name := meta.DisplayName
	if name == "" {
		name = s.Suite
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s W3C conformance results\n\n", name)
	fmt.Fprintf(&b, "Generated by `go run ./cmd/w3ctest %s` in the helium-w3c-tests module.\n", s.Suite)
	fmt.Fprintf(&b, "This is a point-in-time snapshot; regenerate to refresh.\n\n")
	if meta.GeneratedAt != "" {
		fmt.Fprintf(&b, "- Generated: %s\n", meta.GeneratedAt)
	}
	if meta.UpstreamRepo != "" {
		fmt.Fprintf(&b, "- Upstream suite: %s", meta.UpstreamRepo)
		if meta.UpstreamCommit != "" {
			fmt.Fprintf(&b, " @ `%s`", meta.UpstreamCommit)
		}
		b.WriteString("\n")
	}
	if meta.HeliumCommit != "" {
		fmt.Fprintf(&b, "- helium: `%s`\n", meta.HeliumCommit)
	}
	if meta.HarnessCommit != "" {
		fmt.Fprintf(&b, "- helium-w3c-tests (harness): `%s`\n", meta.HarnessCommit)
	}
	if meta.GoVersion != "" {
		fmt.Fprintf(&b, "- Go: `%s`\n", meta.GoVersion)
	}
	if meta.Mode != "" {
		fmt.Fprintf(&b, "- Run mode: %s\n", meta.Mode)
	}

	b.WriteString("\n| Outcome | Count |\n|---------|------:|\n")
	fmt.Fprintf(&b, "| Pass | %d |\n", s.Passed)
	fmt.Fprintf(&b, "| Skip | %d |\n", s.Skipped)
	if s.XFailed > 0 {
		fmt.Fprintf(&b, "| XFail (documented gap) | %d |\n", s.XFailed)
	}
	fmt.Fprintf(&b, "| Fail | %d |\n", s.Failed)
	fmt.Fprintf(&b, "| **Total** | **%d** |\n", s.Total)

	if len(s.SkipReasons) > 0 {
		b.WriteString("\n## Skipped by reason\n\n| Reason | Count |\n|--------|------:|\n")
		type kv struct {
			reason string
			count  int
		}
		rows := make([]kv, 0, len(s.SkipReasons))
		for r, c := range s.SkipReasons {
			rows = append(rows, kv{r, c})
		}
		sort.Slice(rows, func(i, j int) bool {
			if rows[i].count != rows[j].count {
				return rows[i].count > rows[j].count
			}
			return rows[i].reason < rows[j].reason
		})
		for _, row := range rows {
			fmt.Fprintf(&b, "| %s | %d |\n", escapeMarkdownCell(row.reason), row.count)
		}
	}

	if len(s.XFailReasons) > 0 {
		b.WriteString("\n## Expected failures by reason\n\nDocumented known gaps: the harness expects these to fail and treats an unexpected pass as an error.\n\n| Reason | Count |\n|--------|------:|\n")
		type kv struct {
			reason string
			count  int
		}
		rows := make([]kv, 0, len(s.XFailReasons))
		for r, c := range s.XFailReasons {
			rows = append(rows, kv{r, c})
		}
		sort.Slice(rows, func(i, j int) bool {
			if rows[i].count != rows[j].count {
				return rows[i].count > rows[j].count
			}
			return rows[i].reason < rows[j].reason
		})
		for _, row := range rows {
			fmt.Fprintf(&b, "| %s | %d |\n", escapeMarkdownCell(row.reason), row.count)
		}
	}

	_, err := io.WriteString(w, b.String())
	return err
}

// xfailReason reports whether a passing subtest is a harness-recorded expected
// failure (a documented known gap) and returns its reason. The suite logs
// `xfail (<reason>): <details>` via t.Logf on such a case; the subtest passes
// because it failed as expected, so this signal distinguishes an expected
// failure from a genuine pass.
func xfailReason(output []string) (string, bool) {
	const marker = "xfail ("
	for _, line := range output {
		i := strings.Index(line, marker)
		if i < 0 {
			continue
		}
		rest := line[i+len(marker):]
		// The reason itself may contain parentheses; it is terminated by the
		// "): " that precedes the logged details.
		if j := strings.Index(rest, "): "); j >= 0 {
			return strings.TrimSpace(rest[:j]), true
		}
		return strings.TrimSpace(strings.TrimRight(rest, ")\n")), true
	}
	return "", false
}

func escapeMarkdownCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	return strings.ReplaceAll(s, "\n", " ")
}
