// Code generated by w3cgen; DO NOT EDIT.

package xsd_test

var xstsSunCases = []xstsCase{
	{
		ID:          "sunMeta/ElemDecl.testSet/idconstrdefs00301m",
		SchemaRel:   "sunData/ElemDecl/identityConstraintDefs/idConstrDefs00301m/idConstrDefs00301m.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "idConstrDefs00301m1_p", Rel: "sunData/ElemDecl/identityConstraintDefs/idConstrDefs00301m/idConstrDefs00301m1_p.xml", Valid: true},
			{Name: "idConstrDefs00301m2_n", Rel: "sunData/ElemDecl/identityConstraintDefs/idConstrDefs00301m/idConstrDefs00301m2_n.xml", Valid: true},
			{Name: "idConstrDefs00301m3_n", Rel: "sunData/ElemDecl/identityConstraintDefs/idConstrDefs00301m/idConstrDefs00301m3_n.xml", Valid: false},
			{Name: "idConstrDefs00301m4_n", Rel: "sunData/ElemDecl/identityConstraintDefs/idConstrDefs00301m/idConstrDefs00301m4_n.xml", Valid: false},
		},
	},
	{
		ID:          "sunMeta/ElemDecl.testSet/valueconstraint01001m2",
		SchemaRel:   "sunData/ElemDecl/valueConstraint/valueConstraint01001m/valueConstraint01001m2.xsd",
		SchemaValid: true,
	},
	{
		ID:          "sunMeta/ElemDecl.testSet/valueconstraint01001m3",
		SchemaRel:   "sunData/ElemDecl/valueConstraint/valueConstraint01001m/valueConstraint01001m3.xsd",
		SchemaValid: true,
	},
	{
		ID:          "sunMeta/ElemDecl.testSet/valueconstraint01001m5",
		SchemaRel:   "sunData/ElemDecl/valueConstraint/valueConstraint01001m/valueConstraint01001m5.xsd",
		SchemaValid: true,
	},
	{
		ID:          "sunMeta/ElemDecl.testSet/valueconstraint01001m6",
		SchemaRel:   "sunData/ElemDecl/valueConstraint/valueConstraint01001m/valueConstraint01001m6.xsd",
		SchemaValid: true,
	},
	{
		ID:          "sunMeta/MGroup.testSet/particles00104m1",
		SchemaRel:   "sunData/MGroup/particles/particles00104m/particles00104m1.xsd",
		SchemaValid: true,
	},
}

func init() { xstsAllCases = append(xstsAllCases, xstsSunCases...) }
