// Code generated by w3cgen; DO NOT EDIT.

package xsd_test

var xstsWgCases = []xstsCase{
	{
		ID:          "wgMeta/substitution-groups.testSet/sg-and-defined-Sibling-1",
		SchemaRel:   "wgData/sg/snneg.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "sn", Rel: "wgData/sg/sn.xml", Valid: true},
			{Name: "s1n", Rel: "wgData/sg/s1n.xml", Valid: true},
			{Name: "sn1", Rel: "wgData/sg/sn1.xml", Valid: false},
			{Name: "sne", Rel: "wgData/sg/sne.xml", Valid: true},
			{Name: "snn", Rel: "wgData/sg/snn.xml", Valid: false},
			{Name: "sns", Rel: "wgData/sg/sns.xml", Valid: false},
			{Name: "snn1", Rel: "wgData/sg/snn1.xml", Valid: true},
			{Name: "sns1", Rel: "wgData/sg/sns1.xml", Valid: false},
		},
	},
	{
		ID:          "wgMeta/substitution-groups.testSet/sg-and-defined-Sibling-2",
		SchemaRel:   "wgData/sg/negsn.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "esn", Rel: "wgData/sg/esn.xml", Valid: true},
			{Name: "nsn", Rel: "wgData/sg/nsn.xml", Valid: false},
			{Name: "ssn", Rel: "wgData/sg/ssn.xml", Valid: false},
			{Name: "n1sn", Rel: "wgData/sg/n1sn.xml", Valid: true},
			{Name: "s1sn", Rel: "wgData/sg/s1sn.xml", Valid: false},
		},
	},
	{
		ID:          "wgMeta/substitution-groups.testSet/sg-and-defined-Sibling-3",
		SchemaRel:   "wgData/sg/snbranch.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "sns1a", Rel: "wgData/sg/sns1a.xml", Valid: false},
			{Name: "sns1b", Rel: "wgData/sg/sns1b.xml", Valid: true},
			{Name: "sns1c", Rel: "wgData/sg/sns1c.xml", Valid: false},
			{Name: "snn1a", Rel: "wgData/sg/snn1a.xml", Valid: false},
			{Name: "snn1b", Rel: "wgData/sg/snn1b.xml", Valid: false},
			{Name: "snn1c", Rel: "wgData/sg/snn1c.xml", Valid: true},
			{Name: "snea", Rel: "wgData/sg/snea.xml", Valid: true},
			{Name: "sneb", Rel: "wgData/sg/sneb.xml", Valid: false},
			{Name: "snec", Rel: "wgData/sg/snec.xml", Valid: false},
		},
	},
	{
		ID:          "wgMeta/substitution-groups.testSet/sg-abstract-upa",
		SchemaRel:   "wgData/sg/upa.xsd",
		SchemaValid: false,
		Instances: []xstsInstance{
			{Name: "e1.xml", Rel: "wgData/sg/e1.xml", Valid: true},
			{Name: "e1token.xml", Rel: "wgData/sg/e1token.xml", Valid: true},
			{Name: "e1short.xml", Rel: "wgData/sg/e1short.xml", Valid: false},
		},
	},
	{
		ID:          "wgMeta/substitution-groups.testSet/sg-abstract-upa2",
		SchemaRel:   "wgData/sg/upa2.xsd",
		SchemaValid: false,
		Instances: []xstsInstance{
			{Name: "e1.xml", Rel: "wgData/sg/e1.xml", Valid: false},
			{Name: "e1bis.xml", Rel: "wgData/sg/e1.xml", Valid: true},
			{Name: "e1token.xml", Rel: "wgData/sg/e1token.xml", Valid: false},
			{Name: "e1short.xml", Rel: "wgData/sg/e1short.xml", Valid: true},
		},
	},
	{
		ID:          "wgMeta/substitution-groups.testSet/sg-abstract-edc",
		SchemaRel:   "wgData/sg/edc.xsd",
		SchemaValid: false,
		Instances: []xstsInstance{
			{Name: "ee1s.xml", Rel: "wgData/sg/ee1s.xml", Valid: false},
			{Name: "ee1t.xml", Rel: "wgData/sg/ee1t.xml", Valid: false},
			{Name: "ee1i.xml", Rel: "wgData/sg/ee1i.xml", Valid: true},
			{Name: "e1se1s.xml", Rel: "wgData/sg/e1se1s.xml", Valid: false},
			{Name: "e1se1t.xml", Rel: "wgData/sg/e1se1t.xml", Valid: false},
			{Name: "e1ie1s.xml", Rel: "wgData/sg/e1ie1s.xml", Valid: false},
			{Name: "e1ie1t.xml", Rel: "wgData/sg/e1ie1t.xml", Valid: false},
		},
	},
	{
		ID:          "wgMeta/IRI.testSet/iri-001",
		SchemaRel:   "wgData/iri/ElementDeclarations.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "URI-3986-valid-001", Rel: "wgData/iri/URI-3986-valid-001.xml", Valid: true},
			{Name: "URI-3986-valid-002", Rel: "wgData/iri/URI-3986-valid-002.xml", Valid: true},
			{Name: "URI-3986-valid-003", Rel: "wgData/iri/URI-3986-valid-003.xml", Valid: true},
			{Name: "URI-3986-invalid-001", Rel: "wgData/iri/URI-3986-invalid-001.xml", Valid: false},
			{Name: "URI-3986-invalid-002", Rel: "wgData/iri/URI-3986-invalid-002.xml", Valid: false},
			{Name: "URI-3986-invalid-003", Rel: "wgData/iri/URI-3986-invalid-003.xml", Valid: false},
			{Name: "absolute-URI-3986-valid-001", Rel: "wgData/iri/absolute-URI-3986-valid-001.xml", Valid: true},
			{Name: "absolute-URI-3986-valid-002", Rel: "wgData/iri/absolute-URI-3986-valid-002.xml", Valid: true},
			{Name: "absolute-URI-3986-valid-003", Rel: "wgData/iri/absolute-URI-3986-valid-003.xml", Valid: true},
			{Name: "absolute-URI-3986-invalid-001", Rel: "wgData/iri/absolute-URI-3986-invalid-001.xml", Valid: false},
			{Name: "absolute-URI-3986-invalid-002", Rel: "wgData/iri/absolute-URI-3986-invalid-002.xml", Valid: false},
			{Name: "absolute-URI-3986-invalid-003", Rel: "wgData/iri/absolute-URI-3986-invalid-003.xml", Valid: false},
		},
	},
}

func init() { xstsAllCases = append(xstsAllCases, xstsWgCases...) }
