// Code generated by w3cgen; DO NOT EDIT.

package xsd_test

var xstsMsCases = []xstsCase{
	{
		ID:          "msMeta/Additional_w3c.xml/addB078",
		SchemaRel:   "msData/additional/addB078.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Additional_w3c.xml/addB078A",
		SchemaRel:   "msData/additional/addB078.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Additional_w3c.xml/addB078B",
		SchemaRel:   "msData/additional/addB078.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Additional_w3c.xml/addB095",
		SchemaRel:   "msData/additional/addB095.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Additional_w3c.xml/addB118",
		SchemaRel:   "msData/additional/test74966.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Additional_w3c.xml/addB121",
		SchemaRel:   "msData/additional/addB121.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Additional_w3c.xml/addB153",
		SchemaRel:   "msData/additional/test86490_a.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Additional_w3c.xml/isDefault060_2",
		SchemaRel:   "msData/additional/test95960_2.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Additional_w3c.xml/isDefault069",
		SchemaRel:   "msData/additional/test95960_2.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/AttributeGroup_w3c.xml/attgC010",
		SchemaRel:   "msData/attributeGroup/attgC010.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "attgC010a", Rel: "msData/attributeGroup/attgC010a.xml", Valid: true},
			{Name: "attgC010b", Rel: "msData/attributeGroup/attgC010b.xml", Valid: false},
		},
	},
	{
		ID:          "msMeta/AttributeGroup_w3c.xml/attgC020",
		SchemaRel:   "msData/attributeGroup/attgC020.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/AttributeGroup_w3c.xml/attgC031",
		SchemaRel:   "msData/attributeGroup/attgC031.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/AttributeGroup_w3c.xml/attgD015",
		SchemaRel:   "msData/attributeGroup/attgD015.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Attribute_w3c.xml/attKb009",
		SchemaRel:   "msData/attribute/attKb009.xsd",
		SchemaValid: false,
	},
	{
		ID:          "msMeta/Attribute_w3c.xml/attKc009",
		SchemaRel:   "msData/attribute/attKc009.xsd",
		SchemaValid: false,
	},
	{
		ID:          "msMeta/Attribute_w3c.xml/attP029",
		SchemaRel:   "msData/attribute/attP029.xsd",
		SchemaValid: false,
		Instances: []xstsInstance{
			{Name: "attP029.v", Rel: "msData/attribute/attP029.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Attribute_w3c.xml/attP031",
		SchemaRel:   "msData/attribute/attP031.xsd",
		SchemaValid: false,
		Instances: []xstsInstance{
			{Name: "attP031.i", Rel: "msData/attribute/attP031.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Attribute_w3c.xml/attZ013a",
		SchemaRel:   "msData/attribute/attZ013a.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Attribute_w3c.xml/attZ013b",
		SchemaRel:   "msData/attribute/attZ013b.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Attribute_w3c.xml/attZ014a",
		SchemaRel:   "msData/attribute/attZ014a.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "attZ014a.i", Rel: "msData/attribute/attZ014a.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Attribute_w3c.xml/attZ014b",
		SchemaRel:   "msData/attribute/attZ014b.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "attZ014b.i", Rel: "msData/attribute/attZ014b.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/ComplexType_w3c.xml/ctM004",
		SchemaRel:   "msData/complexType/ctM004.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/DataTypes_w3c.xml/anyURI_a001_1336",
		SchemaRel:   "msData/datatypes/Facets/anyURI/anyURI_a001.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "anyURI_a001_1336.v", Rel: "msData/datatypes/Facets/anyURI/anyURI_a001.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/DataTypes_w3c.xml/anyURI_a003_1338",
		SchemaRel:   "msData/datatypes/Facets/anyURI/anyURI_a003.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/DataTypes_w3c.xml/anyURI_b004_1354",
		SchemaRel:   "msData/datatypes/Facets/anyURI/anyURI_b004.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "anyURI_b004_1354.v", Rel: "msData/datatypes/Facets/anyURI/anyURI_b004.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/DataTypes_w3c.xml/anyURI_b006_1356",
		SchemaRel:   "msData/datatypes/Facets/anyURI/anyURI_b006.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "anyURI_b006_1356.i", Rel: "msData/datatypes/Facets/anyURI/anyURI_b006.xml", Valid: false},
		},
	},
	{
		ID:          "msMeta/DataTypes_w3c.xml/float018_1917",
		SchemaRel:   "msData/datatypes/float.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "float018_1917.i", Rel: "msData/datatypes/float018.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/DataTypes_w3c.xml/double018_1956",
		SchemaRel:   "msData/datatypes/double.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "double018_1956.i", Rel: "msData/datatypes/double018.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/DataTypes_w3c.xml/dateTime011_2008",
		SchemaRel:   "msData/datatypes/dateTime.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "dateTime011_2008.i", Rel: "msData/datatypes/dateTime011.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/DataTypes_w3c.xml/dtZ107447_a_2245",
		SchemaRel:   "msData/datatypes/test107447_a.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "dtZ107447_a_2245.i", Rel: "msData/datatypes/test107447.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Element_w3c.xml/elemZ016",
		SchemaRel:   "msData/element/elemZ016.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "elemZ016.i", Rel: "msData/element/elemZ016.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Element_w3c.xml/elemZ032a",
		SchemaRel:   "msData/element/elemZ032a.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Element_w3c.xml/elemZ032b",
		SchemaRel:   "msData/element/elemZ032b.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Group_w3c.xml/groupH021v",
		SchemaRel:   "msData/group/groupH021.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/IdentityConstraint_w3c.xml/idZ011",
		SchemaRel:   "msData/identityConstraint/idZ011.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "idZ011.i", Rel: "msData/identityConstraint/idZ011.xml", Valid: false},
		},
	},
	{
		ID:          "msMeta/ModelGroups_w3c.xml/mgA016",
		SchemaRel:   "msData/modelGroups/mgA016.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/ModelGroups_w3c.xml/mgO001",
		SchemaRel:   "msData/modelGroups/mgO001.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/ModelGroups_w3c.xml/mgO018",
		SchemaRel:   "msData/modelGroups/mgO018.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Particles_w3c.xml/particlesFb003",
		SchemaRel:   "msData/particles/particlesFb003.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Particles_w3c.xml/particlesHa161",
		SchemaRel:   "msData/particles/particlesHa161.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Particles_w3c.xml/particlesHb008",
		SchemaRel:   "msData/particles/particlesHb008.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Particles_w3c.xml/particlesHb011",
		SchemaRel:   "msData/particles/particlesHb011.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Particles_w3c.xml/particlesS002",
		SchemaRel:   "msData/particles/particlesS002.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Particles_w3c.xml/particlesT002",
		SchemaRel:   "msData/particles/particlesT002.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Particles_w3c.xml/particlesT009",
		SchemaRel:   "msData/particles/particlesT009.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Particles_w3c.xml/particlesZ001",
		SchemaRel:   "msData/particles/particlesZ001.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "particlesZ001.i", Rel: "msData/particles/particlesZ001.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Particles_w3c.xml/particlesZ023",
		SchemaRel:   "msData/particles/particlesZ023.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Particles_w3c.xml/particlesZ024",
		SchemaRel:   "msData/particles/particlesZ024.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Particles_w3c.xml/particlesZ028",
		SchemaRel:   "msData/particles/particlesZ028.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Particles_w3c.xml/particlesZ031",
		SchemaRel:   "msData/particles/particlesZ031.xsd",
		SchemaValid: false,
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reF20",
		SchemaRel:   "msData/regex/reF20.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reF20.i", Rel: "msData/regex/reF20.xml", Valid: false},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reF21",
		SchemaRel:   "msData/regex/reF21.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reF21.i", Rel: "msData/regex/reF21.xml", Valid: false},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reF22",
		SchemaRel:   "msData/regex/reF22.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reF22.i", Rel: "msData/regex/reF22.xml", Valid: false},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reF23",
		SchemaRel:   "msData/regex/reF23.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reF23.i", Rel: "msData/regex/reF23.xml", Valid: false},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reG26",
		SchemaRel:   "msData/regex/reG26.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reG26.v", Rel: "msData/regex/reG26.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reG27",
		SchemaRel:   "msData/regex/reG27.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reG27.v", Rel: "msData/regex/reG27.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reG28",
		SchemaRel:   "msData/regex/reG28.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reG28.v", Rel: "msData/regex/reG28.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reG29",
		SchemaRel:   "msData/regex/reG29.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reG29.v", Rel: "msData/regex/reG29.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reG30",
		SchemaRel:   "msData/regex/reG30.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reG30.v", Rel: "msData/regex/reG30.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reG31",
		SchemaRel:   "msData/regex/reG31.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reG31.v", Rel: "msData/regex/reG31.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reG32",
		SchemaRel:   "msData/regex/reG32.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reG32.v", Rel: "msData/regex/reG32.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reG33",
		SchemaRel:   "msData/regex/reG33.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reG33.v", Rel: "msData/regex/reG33.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reH19",
		SchemaRel:   "msData/regex/reH19.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reH19.v", Rel: "msData/regex/reH19.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reH20",
		SchemaRel:   "msData/regex/reH20.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reH20.i", Rel: "msData/regex/reH20.xml", Valid: false},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reH21",
		SchemaRel:   "msData/regex/reH21.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reH21.i", Rel: "msData/regex/reH21.xml", Valid: false},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reK88",
		SchemaRel:   "msData/regex/reK88.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reK88.v", Rel: "msData/regex/reK88.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Regex_w3c.xml/reZ006i",
		SchemaRel:   "msData/regex/schema_c.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "reZ006i.i", Rel: "msData/regex/invalid.c.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Schema_w3c.xml/schL3",
		SchemaRel:   "msData/schema/schL3_a.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/Schema_w3c.xml/schL5",
		SchemaRel:   "msData/schema/schL5_a.xsd",
		SchemaValid: true,
	},
	{
		ID:          "msMeta/SimpleType_w3c.xml/stE053",
		SchemaRel:   "msData/simpleType/stE053.xsd",
		SchemaValid: false,
		Instances: []xstsInstance{
			{Name: "stE053.i", Rel: "msData/simpleType/stE053.xml", Valid: false},
		},
	},
	{
		ID:          "msMeta/SimpleType_w3c.xml/stZ007",
		SchemaRel:   "msData/simpleType/stZ007.xsd",
		SchemaValid: false,
		Instances: []xstsInstance{
			{Name: "stZ007.v", Rel: "msData/simpleType/stZ007.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/SimpleType_w3c.xml/stZ047",
		SchemaRel:   "msData/simpleType/test107331_e.xsd",
		SchemaValid: false,
		Instances: []xstsInstance{
			{Name: "stZ047.v", Rel: "msData/simpleType/test107331_4.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/SimpleType_w3c.xml/stZ055",
		SchemaRel:   "msData/simpleType/test107331_e.xsd",
		SchemaValid: false,
		Instances: []xstsInstance{
			{Name: "stZ055.v", Rel: "msData/simpleType/test107331_9.xml", Valid: true},
		},
	},
	{
		ID:          "msMeta/Wildcards_w3c.xml/wildZ013",
		SchemaRel:   "msData/wildcards/test328873i.xsd",
		SchemaValid: true,
	},
}

func init() { xstsAllCases = append(xstsAllCases, xstsMsCases...) }
