// Code generated by w3cgen; DO NOT EDIT.

package xsd_test

var xstsOracleCases = []xstsCase{
	{
		ID:          "oracleMeta/Zone.testSet/zone401",
		SchemaRel:   "oracleData/Zone/zone401.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "zone401.v1.xml", Rel: "oracleData/Zone/zone401.v1.xml", Valid: true},
			{Name: "zone401.v2.xml", Rel: "oracleData/Zone/zone401.v2.xml", Valid: true},
			{Name: "zone401.v3.xml", Rel: "oracleData/Zone/zone401.v3.xml", Valid: true},
			{Name: "zone401.n1.xml", Rel: "oracleData/Zone/zone401.n1.xml", Valid: false},
			{Name: "zone401.n2.xml", Rel: "oracleData/Zone/zone401.n2.xml", Valid: false},
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone402",
		SchemaRel:   "oracleData/Zone/zone402.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "zone402.n1.xml", Rel: "oracleData/Zone/zone402.n1.xml", Valid: false},
			{Name: "zone402.n2.xml", Rel: "oracleData/Zone/zone402.n2.xml", Valid: false},
			{Name: "zone402.v1.xml", Rel: "oracleData/Zone/zone402.v1.xml", Valid: true},
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone403",
		SchemaRel:   "oracleData/Zone/zone403.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "zone403.v1.xml", Rel: "oracleData/Zone/zone403.v1.xml", Valid: true},
			{Name: "zone403.v2.xml", Rel: "oracleData/Zone/zone403.v2.xml", Valid: true},
			{Name: "zone403.n1.xml", Rel: "oracleData/Zone/zone403.n1.xml", Valid: false},
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone404",
		SchemaRel:   "oracleData/Zone/zone404.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "zone404.v1.xml", Rel: "oracleData/Zone/zone404.v1.xml", Valid: true},
			{Name: "zone404.n1.xml", Rel: "oracleData/Zone/zone404.n1.xml", Valid: false},
			{Name: "zone404.n2.xml", Rel: "oracleData/Zone/zone404.n2.xml", Valid: false},
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone405",
		SchemaRel:   "oracleData/Zone/zone405.xsd",
		SchemaValid: true,
		Instances: []xstsInstance{
			{Name: "zone405.v1.xml", Rel: "oracleData/Zone/zone405.v1.xml", Valid: true},
			{Name: "zone405.v2.xml", Rel: "oracleData/Zone/zone405.v2.xml", Valid: true},
			{Name: "zone405.v3.xml", Rel: "oracleData/Zone/zone405.v3.xml", Valid: true},
		},
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone406",
		SchemaRel:   "oracleData/Zone/zone406.bad.xsd",
		SchemaValid: false,
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone407",
		SchemaRel:   "oracleData/Zone/zone407.bad.xsd",
		SchemaValid: false,
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone408",
		SchemaRel:   "oracleData/Zone/zone408.bad.xsd",
		SchemaValid: false,
	},
	{
		ID:          "oracleMeta/Zone.testSet/zone409",
		SchemaRel:   "oracleData/Zone/zone409.bad.xsd",
		SchemaValid: false,
	},
}

func init() { xstsAllCases = append(xstsAllCases, xstsOracleCases...) }
