// Code generated by w3cgen; DO NOT EDIT.

package xsd_test

import (
	"os"
	"testing"

	"github.com/lestrrat-go/helium-w3c-tests/internal/harness"
)

const w3cSuiteName = "xsd11"
const w3cDisplayName = "XSD 1.1"
const w3cSourceKind = "git"
const w3cSourceRepo = "https://github.com/w3c/xsdtests.git"
const w3cSourceURL = ""
const w3cPinnedCommit = "7bc3365c652a322f3d762021b3879eb92dae7e30"
const w3cSourceDir = "sources/xsd11"
const w3cCatalogPath = "sources/xsd11/suite.xml"
const w3cCatalogTestSets = 93
const w3cCatalogTestCases = 967
const w3cRunnableTestCases = 967
const w3cSkippedTestCases = 0
const w3cExcludedTestCases = 0

func TestXSD11W3CManifestAvailable(t *testing.T) {
	t.Parallel()
	sourcePath := harness.SourceDir(t, w3cSourceDir)
	if _, err := os.Stat(sourcePath); err != nil {
		if os.IsNotExist(err) {
			t.Skipf("%s source tree not fetched; run %s", w3cDisplayName, "go run ./cmd/w3cgen fetch xsd11")
		}
		t.Fatalf("stat %s source tree: %v", w3cDisplayName, err)
	}
	if w3cCatalogPath == "" {
		t.Logf("%s source tree present at %s; no catalog file was found", w3cDisplayName, sourcePath)
		return
	}
	t.Logf("%s catalog %s: %d test sets, %d test cases (%d runnable, %d skipped, %d excluded)", w3cDisplayName, w3cCatalogPath, w3cCatalogTestSets, w3cCatalogTestCases, w3cRunnableTestCases, w3cSkippedTestCases, w3cExcludedTestCases)
}
