// Code generated by w3cgen; DO NOT EDIT.

package xsd_test

import (
	"testing"

	helium "github.com/lestrrat-go/helium"
	"github.com/lestrrat-go/helium/xsd"
)

func TestXSD11SmokeDoublePositiveInfinity(t *testing.T) {
	t.Parallel()
	schemaXML := "<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\n  <xs:element name=\"value\" type=\"xs:double\"/>\n</xs:schema>"
	instanceXML := "<value>+INF</value>"
	schemaDoc, err := helium.NewParser().Parse(t.Context(), []byte(schemaXML))
	if err != nil {
		t.Fatalf("parse schema: %v", err)
	}
	schema, err := xsd.NewCompiler().Label("xsd11-smoke.xsd").Compile(t.Context(), schemaDoc)
	if err != nil {
		t.Fatalf("compile schema: %v", err)
	}
	instanceDoc, err := helium.NewParser().Parse(t.Context(), []byte(instanceXML))
	if err != nil {
		t.Fatalf("parse instance: %v", err)
	}
	if err := xsd.NewValidator(schema).Label("xsd11-smoke.xml").Validate(t.Context(), instanceDoc); err != nil {
		t.Fatalf("validate +INF as xs:double: %v", err)
	}
}
