package generator

import (
	"fmt"
	"strconv"
	"strings"
)

type ManifestTest struct {
	PackageName  string
	TestName     string
	DisplayName  string
	SuiteName    string
	FetchCommand string
	Lock         SuiteLock
	Catalog      CatalogInfo
}

func ManifestTestSource(test ManifestTest) string {
	var b strings.Builder
	b.WriteString("// Code generated by w3cgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", test.PackageName)
	b.WriteString("import (\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"testing\"\n\n")
	b.WriteString("\t\"github.com/lestrrat-go/helium-w3c-tests/internal/harness\"\n")
	b.WriteString(")\n\n")
	fmt.Fprintf(&b, "const w3cSuiteName = %s\n", strconv.Quote(test.SuiteName))
	fmt.Fprintf(&b, "const w3cDisplayName = %s\n", strconv.Quote(test.DisplayName))
	fmt.Fprintf(&b, "const w3cSourceKind = %s\n", strconv.Quote(test.Lock.SourceKind()))
	fmt.Fprintf(&b, "const w3cSourceRepo = %s\n", strconv.Quote(test.Lock.Repo))
	fmt.Fprintf(&b, "const w3cSourceURL = %s\n", strconv.Quote(test.Lock.URL))
	fmt.Fprintf(&b, "const w3cPinnedCommit = %s\n", strconv.Quote(test.Lock.Commit))
	fmt.Fprintf(&b, "const w3cSourceDir = %s\n", strconv.Quote(test.Lock.SourceDir))
	fmt.Fprintf(&b, "const w3cCatalogPath = %s\n", strconv.Quote(test.Catalog.CatalogPath))
	fmt.Fprintf(&b, "const w3cCatalogTestSets = %d\n", test.Catalog.TestSetCount)
	fmt.Fprintf(&b, "const w3cCatalogTestCases = %d\n", test.Catalog.TestCaseCount)
	fmt.Fprintf(&b, "const w3cRunnableTestCases = %d\n", test.Catalog.RunnableCount)
	fmt.Fprintf(&b, "const w3cSkippedTestCases = %d\n", test.Catalog.SkippedCount)
	fmt.Fprintf(&b, "const w3cExcludedTestCases = %d\n\n", test.Catalog.ExcludedCount)
	fmt.Fprintf(&b, "func %s(t *testing.T) {\n", test.TestName)
	b.WriteString("\tt.Parallel()\n")
	b.WriteString("\tsourcePath := harness.SourceDir(t, w3cSourceDir)\n")
	b.WriteString("\tif _, err := os.Stat(sourcePath); err != nil {\n")
	b.WriteString("\t\tif os.IsNotExist(err) {\n")
	fmt.Fprintf(&b, "\t\t\tt.Skipf(\"%%s source tree not fetched; run %%s\", w3cDisplayName, %s)\n", strconv.Quote(test.FetchCommand))
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tt.Fatalf(\"stat %s source tree: %v\", w3cDisplayName, err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif w3cCatalogPath == \"\" {\n")
	b.WriteString("\t\tt.Logf(\"%s source tree present at %s; no catalog file was found\", w3cDisplayName, sourcePath)\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n")
	b.WriteString("\tt.Logf(\"%s catalog %s: %d test sets, %d test cases (%d runnable, %d skipped, %d excluded)\", w3cDisplayName, w3cCatalogPath, w3cCatalogTestSets, w3cCatalogTestCases, w3cRunnableTestCases, w3cSkippedTestCases, w3cExcludedTestCases)\n")
	b.WriteString("}\n")
	return b.String()
}
